### ISSUE TITLE
Handle ABI Splits

### ISSUE THREAD

**Issue by xiphirx** [KeepSafe/dexcount-gradle-plugin#101]
If you enable ABI splits in your gradle build file, you get duplicate output per ABI from this plugin. This is unnecessary as each split has the exact same method and field counts. We should figure out if there is a way to determine if ABI splitting is enabled and handle it accordingly. 

Here's some sample "bad" output:

```
:app:countArmeabi-v7aDebugDexMethods
Total methods in app-armeabi-v7a-debug.apk: 51427 (78.47% used)
Total fields in app-armeabi-v7a-debug.apk:  26962 (41.14% used)
Methods remaining in app-armeabi-v7a-debug.apk: 14108
Fields remaining in app-armeabi-v7a-debug.apk:  38573
:app:countArmeabiDebugDexMethods
Total methods in app-armeabi-debug.apk: 51427 (78.47% used)
Total fields in app-armeabi-debug.apk:  26962 (41.14% used)
Methods remaining in app-armeabi-debug.apk: 14108
Fields remaining in app-armeabi-debug.apk:  38573
:app:countX86DebugDexMethods
Total methods in app-x86-debug.apk: 51427 (78.47% used)
Total fields in app-x86-debug.apk:  26962 (41.14% used)
Methods remaining in app-x86-debug.apk: 14108
Fields remaining in app-x86-debug.apk:  38573
```

**Comment by benjamin-bader** [comment]
What immediately jumps to my mind is that splits are represented in the Gradle build model as a simple Variant.  Can we distinguish a split variant from, say, a `debug` flavor that has extra debugging code?

**Comment by xiphirx** [comment]
I'm not entirely sure what you're talking about since ABI splits happen on every variant combo possible. I think we can determine whether or not we're on the same variant but are just splitting the ABI based on the task name at the very least. I haven't looked into this at all yet.

**Comment by benjamin-bader** [comment]
I poked around a little more, and as it happens this will be quite easy to fix - I misunderstood the issue before.  PR incoming.

**Comment by benjamin-bader** [comment]
...nope, never mind.  misread something - this still seems hard to sort out.

**Comment by benjamin-bader** [comment]
Is this still an issue anyone cares about?  Given four years of no comments or even thumbs-ups, I'm inclined to say "no" and mark this as wontfix.
