### ISSUE TITLE
I'm getting this error Cannot change dependencies of configuration

### ISSUE THREAD

**Issue by RobertoIDL** [KeepSafe/dexcount-gradle-plugin#103]
I have copied this:

    buildscript {
        repositories {
            mavenCentral() // or jcenter()
        }

        dependencies {
            classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.5.2'
        }
    }

into my app's gradle file, inside the android block at the bottom. Then I apply the plugin apply plugin: 'com.getkeepsafe.dexcount' after the google services plugin

Any ideas?

**Comment by benjamin-bader** [comment]
I think you've pasted into the wrong place - that belongs at the top of the gradle file, not inside the android block.  Let me know if that helps.

**Comment by benjamin-bader** [comment]
Hi @RobertoIDL, did this help?  Are you still having trouble?

**Comment by benjamin-bader** [comment]
Seems like there is no further issue, so I'll close this one.  Please file another if you have any other problems.
