### ISSUE TITLE
[Feature Request] Add JAR support

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#106]
## Similar to:
https://github.com/KeepSafe/dexcount-gradle-plugin/issues/10.

## Some Background:
A project with Java and Android Library modules.

## Example:
```
$ tree -L 2
.
|-- CHANGELOG.md
|-- LICENSE
|-- README.md
`-- androidLibrary            <-- module
|    |-- build.gradle
|    `-- src
`-- javaLibrary               <-- module
|    |-- build.gradle
|    `-- src
|-- settings.gradle
```

Can we add support for method counts in Jars? Similar to the AAR support?

**Comment by benjamin-bader** [comment]
Theoretically, sure.  I'm personally swamped with other things, and won't have time to think about it for the foreseeable future.  (the usual caveats about accuracy apply here, too).

As always, I'd be happy to look at a good PR!

**Comment by alexblack** [comment]
This would be great. The problem I run into is my project eventually exceeds the dex limit, then I can't build, and then I can't seem to find out what is taking up all the methods since I don't get a dex count output.

**Comment by jaredsburrows** [comment]
@alexblack This plugin works with multidex for android.

**Comment by benjamin-bader** [comment]
Just to add to Jared's point, presumably you know precisely when your build exceeded the method limit, via commit history.  It might even be easier than multidexing to just check out a version that still builds, and count from there.

**Comment by alexblack** [comment]
Thanks, yes, figured that out after :)

**Comment by jaredsburrows** [comment]
After re-reading this issue that I created a while ago, I feel that this plugin, `dexcount-gradle-plugin` is meant to count methods in `*.dex` files. Counting the number of methods in a separate module in the same project seems to be out of scope of what this plugin was originally created for.

Also, when you compile all the modules together to combine to a single `.aar` or `.apk` file, that is when the dex count should be counted and not before.
