### ISSUE TITLE
Gradle 2.14 no longer exposes `org.gradle.logging.ShowStacktrace`

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#109]
Time to figure out what to replace it with.

**Comment by vanniktech** [comment]
@benjamin-bader is there a snapshot in which I could try this workaround out?

**Comment by benjamin-bader** [comment]
0.5.4-SNAPSHOT ought to have the fix.  I'll upload it manually now to be sure.

**Comment by vanniktech** [comment]
Running `./gradlew` works now with `0.5.4-SNAPSHOT`.
