### ISSUE TITLE
Plugin breaks with Gradle 2.14

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#113]
I am using the latest `0.5.3`.

Here is the error after updating to Gradle 2.14:
```
> Failed to notify project evaluation listener.
   > org/gradle/logging/ShowStacktrace
```

http://mvnrepository.com/artifact/com.getkeepsafe.dexcount/dexcount-gradle-plugin

Since `0.5.0` had an issue, I have to revert all the way back to `0.4.4`.

**Comment by benjamin-bader** [comment]
Yup.  I released 0.5.4 a few hours ago to fix.  What do other projects use to announce updates?  We ought to have _something_.

**Comment by benjamin-bader** [comment]
Also FYI, `mvnrepository.com` is unaffiliated with Maven Central, and lags it by anywhere from a few hours to a few days.  `search.maven.org` is a better bet: http://search.maven.org/#artifactdetails|com.getkeepsafe.dexcount|dexcount-gradle-plugin|0.5.4|jar

**Comment by jaredsburrows** [comment]
@benjamin-bader Have you thought of using `jcenter` and syncing with `mavenCentral`?

**Comment by benjamin-bader** [comment]
A long time ago.  I'm very turned off by their public persona, honestly - the marketing/evangelism I've seen has been very misleading and disingenuous.  In addition, I don't see any real advantage to switching.  I've chiefly heard that it is a bit easier to get a new project going on jcenter, but beyond that (and possibly their "faster" CDN), I'm not aware of any extra benefit.  What would be better about jcenter in this case?

**Comment by jaredsburrows** [comment]
Sorry, please do not take it like that. I am just saying it could sync to multiple repos. In my CI builds, I the plugins repo from Gradle:
```
    repositories {
        maven { url "https://plugins.gradle.org/m2/" } // Mirrors jcenter() and mavenCentral()
    }
```
This way, it mirrors both, so if one gets synced faster than the other its ok for the end user.

**Comment by benjamin-bader** [comment]
No worries, just giving you my reason for not choosing JCenter in the past - I'm not at all bothered by the question!  And thanks, I didn't know about Gradle's repo.

I'm not sure I understand what you meant, so maybe this won't be responsive to your question (let me know if that's the case), but it doesn't seem like there's anything to be done.

It sounds like the delay you're referring to is the absence of the update in `mvnrepository.com`.  I had the same confusion a little while ago, and was corrected by one of the Sonatype folks who maintain Maven Central.  `mvnrepository.com` is an entirely separate entity from both JCenter and Maven Central.  The delay in their search results is a result of their own crawler's implementation; no matter which repo we chose, `mvnrepository.com` would always be at least a few hours out of date.

The actual sync time (the time between me clicking the button and the artifact becoming available for download) is very short - on the order of five minutes, usually.

Also, unrelated to the topic, but does 0.5.4 fix your build?

**Comment by jaredsburrows** [comment]
@benjamin-bader Yes, you can close this now. Thanks for the quick fix. `0.5.4` fixes my build.

So once I was using the Google error prone gradle plugin. The maintainer stopped updating his `jcenter` version and kept maintaining the `mavencentral` version. So instead of doing the following:

```
    repositories {
        jcenter()
        mavenCentral()
    }
```

You can do:

```
    repositories {
        maven { url "https://plugins.gradle.org/m2/" } // Mirrors jcenter() and mavenCentral()
    }
```
Which is effectively equivalent to:
```
    repositories {
        jcenter()
        mavenCentral()
        maven { url "https://plugins.gradle.org/m2/" } // Mirrors jcenter() and mavenCentral()
    }
```

It mirrors `jcenter` and `mavencentral` and has the plugin dependencies that support Gradles new `id`.

**Comment by benjamin-bader** [comment]
Interesting!
