### ISSUE TITLE
Add to plugins Gradle repo.

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#114]
Please add to https://plugins.gradle.org.

**Comment by benjamin-bader** [comment]
I'd love to, but there is a bug in their publishing platform that prevents it.  See issue #9 for the details.

**Comment by jaredsburrows** [comment]
@benjamin-bader Wow. It has been open for 1+ years. Please comment on there and here: https://discuss.gradle.org/t/gradle-publish-plugin-fails-if-the-artifacts-are-signed/9197 to get this active again.
