### ISSUE TITLE
`StyledTextOutput` repackaged in Gradle 3.0

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#124]
Per a comment on issue #123.

**Comment by benjamin-bader** [comment]
After investigating, it's not going to be a small task to keep the console-coloring functionality cross-platform.  StyledTextOutput does actually exist in Gradle 3.0, it is merely repackaged.  The problem is that it is now explicitly internal, and subject to this kind of breakage in the future (see https://discuss.gradle.org/t/bug-in-gradle-2-14-rc1-no-service-of-type-styledtextoutputfactory/17638/8).  To preserve existing functionality, we could:

- Do a support-library-style facade wrapper around the various Gradle 2 and Gradle 3 versions of StyleTextOutput and Factory, relying on reflection to choose the appropriate implementation
- Implement console coloring ourselves, possibly using JAnsi (which is what Gradle uses).

I'm leaning towards the latter, as it will be robust to changes in the future.  The downside is that we'll have to maintain mappings between style, log-level, etc. with Gradle, and play nicely e.g. when there isn't an ANSI terminal at the end of stdout, etc.  These are things that Gradle currently does "for free".

Thoughts?

**Comment by smuldr** [comment]
Is there any workaround for this issue with the current 0.5.5 release? For me it would be perfectly fine to have non-styled text output, as long as the plugin keeps working with Gradle 3.0. Maybe with a flag in the configuration to enable/disable?

**Comment by benjamin-bader** [comment]
There is no workaround; we were relying on this one mechanism to print to the console.  I'm personally busy with other work at the moment, but will try to make time for this in the next few days.

Of course, PRs are welcome!

**Comment by xiphirx** [comment]
I think an intermediate step of just reverting to non-stylized text output would be good before we have our own solution.

**Comment by benjamin-bader** [comment]
Sure.  Want to do the honors?

**Comment by xiphirx** [comment]
Sure, PR incoming

**Comment by benjamin-bader** [comment]
Thanks @xiphirx for the quick PR - I'll verify and release a fixed version shortly.

**Comment by benjamin-bader** [comment]
Version 0.5.6, containing the fix for this issue, has just been pushed to Sonatype.  It should be available in Maven Central within the next 10 minutes, and JCenter soon thereafter.
