### ISSUE TITLE
Creating a task for dex counting without actually running it by default

### ISSUE THREAD

**Issue by athkalia** [KeepSafe/dexcount-gradle-plugin#125]
Hello,

I want to include this plugin in my build.gradle so that it's convenient to use it for every developer whenever they need it (probably a few times per year), but I don't want it to run on it's own on every build.
Any suggestion on how to do that without commenting out the "apply plugin" part or without having any sort of environment parameters and an if statement?

I think that this should be configurable in the plugin "dexcount { }" configuration

cheers

**Comment by benjamin-bader** [comment]
The current behavior is that, when applied, the plugin will schedule counting after the `assemble` task; there isn't a way to selectively disable that, short of not applying the plugin.

When would you want it to run/not run?

**Comment by athkalia** [comment]
Hello,

I don't want it to run as part of the assemble task, as that means that it's slowing down every single build for everyone (by just a bit), when it's only really needed once every couple of months or so, when we troubleshoot dex count issues. So what I am suggesting is to have flag in the configuration to disable running it.

Then when I want to run it myself I can run it by calling it's task (I assume there is one right? )

Thanks!

**Comment by benjamin-bader** [comment]
I see.  You could, perhaps, suppress the individual tasks with command-line flags: https://docs.gradle.org/current/userguide/tutorial_gradle_command_line.html#sec:excluding_tasks_from_the_command_line

I'm not inclined to decouple counting from assembly; counting depends on there being an APK to count, and that's not guaranteed if the task is run by itself.  You would be better served either by conditionally applying the plugin, or by using a different tool like [`dex-method-count`](https://github.com/mihaip/dex-method-counts).

**Comment by athkalia** [comment]
You could have your task depend on assembly instead of having it run after assembly. But still keep them separate.

**Comment by benjamin-bader** [comment]
We could implement that, but that's not the behavior most people would expect.  It would be very unusual to apply a plugin, then have nothing happen by default - unless I misunderstand Gradle (it happens!), that's exactly what the outcome would be.

We could add a configuration option to change this behavior, like `runOnEachAssemble = true`.  As long as the default preserves current behavior, I'd be OK with that.  Happy to take a pull request for that one!

**Comment by athkalia** [comment]
yeah that's exactly what I want. A toggle switch so that I can disable it. I can put it on my todo list, but don't expect anything anytime soon, I don't have time to scratch my back these days : >

**Comment by benjamin-bader** [comment]
@sarahlensing's commit with the new `runOnEachAssemble` config option is now released in version 0.6.1; it should be available for use within 15 minutes at most.

**Comment by athkalia** [comment]
<3
