### ISSUE TITLE
Restore colorized output

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#127]
Gradle 3.0 forced us to stop using StyledTextOutput.  Sadly (for me, at least) this means that we lose the green/yellow/red highlighting for the short method counts.

We could add them back by using JAnsi and (potentially) bypassing Gradle's logging system and going directly to stdout.

Questions that need > 0 thought:
- Does Gradle redirect stdout?  If so, can we rely on their `ConsoleOutput` enum to know if we're attached to an ANSI-capable terminal?
- Does it matter if we aren't participating in Gradle's logging system?
- Can we send ANSI-escaped text through Gradle's logging system?  <-- would be awesome

**Comment by xiphirx** [comment]
> Does Gradle redirect stdout? If so, can we rely on their ConsoleOutput enum to know if we're attached to an ANSI-capable terminal?

They do/can via [LoggingManager](https://docs.gradle.org/current/javadoc/org/gradle/api/logging/LoggingManager.html#captureStandardOutput(org.gradle.api.logging.LogLevel)).

> Does it matter if we aren't participating in Gradle's logging system?

I think it only matters up to the point of configuration (user requesting verbosity, etc)

- Can we send ANSI-escaped text through Gradle's logging system? <-- would be awesome

Seems so.
![image](https://cloud.githubusercontent.com/assets/993832/17792547/262922b8-6556-11e6-9ce1-855693f73239.png)

I think doing so is the best solution. If the output / end device does not support ANSI codes and there is a majority of people having issues, then we can deal with that later.

**Comment by benjamin-bader** [comment]
Good find - docs suggest that, by default, they do indeed redirect stdout into their logging framework.  I guess then that we can definitely rely on `ConsoleOutput`, since we've been relying on it unintentionally since day 0!

I agree with you; using ANSI in combination with Gradle's `Logger` seems like the best (and simplest) way to go.

**Comment by xiphirx** [comment]
PR incoming

**Comment by xiphirx** [comment]
I have an almost complete solution here: https://github.com/KeepSafe/dexcount-gradle-plugin/tree/xiphirx/stylize

The problem now is finding an instance of `ConsoleOutput` so I can conditionally disable the coloring...

**Comment by benjamin-bader** [comment]
Hah, of course you'd implement your own ANSI encoding!  (Yes, I know it's simple.)  I have some work in-progress from last night to do this using JAnsi; we can see which approach turns out better.  If we can do it cleanly without an extra dependency, so much the better.

The thing you're looking for is called `StartParameter`.  You can get it from `project.gradle.startParameter`.  It has a method `getConsoleOutput`; I _think_ that this API is stable across all of Gradle 2.X and 3.X (so far); by that I mean I don't think that it has been moved from one package to another.  I think it's safe to say that if the value isn't `Plain`, then we can emit styled output.

**Comment by xiphirx** [comment]
Hm, that value returns `Auto` instead of `Plain` when redirecting output to a file... I'm unsure how Gradle is detecting that it is writing to a file and suppressing color codes. I think it may have to do with how https://github.com/gradle/gradle/blob/master/subprojects/logging/src/main/java/org/gradle/internal/logging/sink/ConsoleConfigureAction.java operates, but attempting to replicate its logic didn't help.

**Comment by benjamin-bader** [comment]
The rabbit hole goes deep on that one.

Probably we could just assume `Auto` means use color - redirecting Gradle output to a file is likely pretty niche.  For those uses we could add a config param to suppress color codes.

**Comment by xiphirx** [comment]
Yeah, can't figure out how Gradle is conditionally suppressing its ANSI codes when the output is a file... I'm not sure if that is something we care about. You can see what I've tried in [my branch](https://github.com/KeepSafe/dexcount-gradle-plugin/tree/xiphirx/stylize)
