### ISSUE TITLE
Add project name (or another custom tag)  to Teamcity log pattern

### ISSUE THREAD

**Issue by georgeci** [KeepSafe/dexcount-gradle-plugin#128]
I have few android projects in one repository. And i run one task for building all projects.
I need some tag to differentiate count statistics for each project.

**Comment by benjamin-bader** [comment]
Easy enough to do.  I don't want to enable this by default because it would break existing TeamCity users.

We could add a config option:

```gradle
dexcount {
  ...
  // probably would default to null, but in your case:
  teamcitySlug = project.name
}
```

Which results in fields like:
`##teamcity[buildStatisticValue key='DexCount_$teamcitySlug_MethodCount' value='${value}']`

**Comment by georgeci** [comment]
It's enough. Thanks!

**Comment by benjamin-bader** [comment]
This will ship in the next release; in the meantime, it should be available in the latest snapshot builds.  Let me know if you find something that isn't working properly.
