### ISSUE TITLE
Think about Proguard support

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#13]
If a mapping exists, we should use it to de-obfuscate package names for method counts.

If you are reading this, and are interested in having support for using Proguard mappings in dexcount output, please leave a +1.  This is currently very low priority, but if enough people are interested we can make it happen sooner.

**Comment by kherembourg** [comment]
+1

**Comment by philbring** [comment]
+1

**Comment by stoyicker** [comment]
+1

**Comment by aegis123** [comment]
+1

**Comment by vanniktech** [comment]
+1

**Comment by fada21** [comment]
+1

**Comment by tomaszrykala** [comment]
+1

**Comment by vovkab** [comment]
+1
