### ISSUE TITLE
Unable to use with gradle-experimental

### ISSUE THREAD

**Issue by IgorGanapolsky** [KeepSafe/dexcount-gradle-plugin#130]
Hello,
I followed your instructions in the README.  However, I am getting the following error:

> java.lang.IllegalArgumentException: Dexcount plugin requires the Android plugin to be configured

Is there something that can be done with gradle experimental?

Igor

**Comment by benjamin-bader** [comment]
This is expected.  `gradle-experimental` is a complete break in terms of the plugin API, and we don't support it at all.

I seem to recall that work on it has been paused for some time; perhaps with Gradle 3.0 they'll resume?  I haven't heard anything to that effect, have you?

**Comment by IgorGanapolsky** [comment]
@benjamin-bader If work on gradle-experimental has been paused, then it's disappointing.  It is the only gradle version that lets you have C++ & jni code alongside Java code in the same project, and let's you debug it with breakpoints...

**Comment by benjamin-bader** [comment]
Agreed.  I think "paused" might be too strong.  "De-prioritized" might be better; I spoke with the build-tools team a few months back and they mentioned that there was a blocking bug in Gradle that might have been fixed in 3.0.  That's obviously been released, so my info might be out-of-date.

**Comment by IgorGanapolsky** [comment]
@jaredsburrows I don't use Gradle Experimental anymore.  So it's a moot issue.

**Comment by jaredsburrows** [comment]
@IgorGanapolsky Thanks!
