### ISSUE TITLE
Publishing to Gradle Plugin Portal	

### ISSUE THREAD

**Issue by danikula** [KeepSafe/dexcount-gradle-plugin#135]
Currently impossible add plugin to build script by 
```
plugins {
    id 'com.getkeepsafe.dexcount' version '0.6.1'
}
```
as described [here](https://gradle.org/blog/new-gradle-plugin-portal/) because plugin is not available at [https://plugins.gradle.org](https://plugins.gradle.org). 

Gradle fails with 
```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/danik/Programming/Projects/edufii/app/build.gradle' line: 18

* What went wrong:
Plugin [id: 'com.getkeepsafe.dexcount', version: '0.6.1'] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Gradle Central Plugin Repository (no 'com.getkeepsafe.dexcount' plugin available - see https://plugins.gradle.org for available plugins)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

**Comment by benjamin-bader** [comment]
Yep, we are definitely not in the Gradle plugin repo.  There's another (closed) issue about this, in which has details about why we aren't - long story short, they have a bug making it difficult to be in both Maven Central and the Gradle plugin repo.  Until they fix that, I'll stick with Maven/jcenter which offer far greater distribution.
