### ISSUE TITLE
Can't run instrumented tests with dexcount-gradle-plugin classpath added

### ISSUE THREAD

**Issue by yankeppey** [KeepSafe/dexcount-gradle-plugin#136]
Hey, first of all thanks for great plugin!

But I've found a very weird issue. When I add
> dependencies {
>     classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.1'
> }

, my instrumented tests (`./gradlew clean connectedAndroidTest`) stop workings, even without plugin applied (line `//apply plugin: 'com.getkeepsafe.dexcount'` is commented). The following message is printed:

> com.android.builder.testing.ConnectedDevice > No tests found.[MotoG3 - 6.0] FAILED 
> No tests found. This usually means that your test classes are not in the form that your test runner > expects (e.g. don't inherit from TestCase or lack @Test annotations).

But that's not true, I have working tests that runs successfully after commenting the line
> classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.1'

Do you have any idea why it happens?

**Comment by benjamin-bader** [comment]
Truly bizarre.  It seems for all the world like a stale build, except that you're `clean`ing before running tests.

Merely listing a classpath dependency *shouldn't* have any impact at all on a build.  Is this reproducible?  I.e. if you uncomment the dependency, do your tests vanish again?

**Comment by yankeppey** [comment]
@benjamin-bader yes, totally reproducible! Also it's worth to mention there are several flavors in my project.

**Comment by yankeppey** [comment]
I understand all the awkwardness of this, and _probably_ it's some combination of factors, not only dexcount (it's being triggered only by changing one line, though).
I would prefer not to share all my files publicly, but feel free to write me to yankeppey on gmail, all my assistance is yours.

**Comment by benjamin-bader** [comment]
Sorry for the delay over the weekend.  I, too, would prefer not to take possession of yours (or your employer's?) private files.

Is this perhaps reducible to a smaller sample project?

**Comment by yankeppey** [comment]
Going to try to do it with few days!

**Comment by yankeppey** [comment]
My test environment is not stable enough. Going to close this issue for now, probably will be able to reproduce later.
