### ISSUE TITLE
Dexcount task is not called for abi split assemble tasks

### ISSUE THREAD

**Issue by vovkab** [KeepSafe/dexcount-gradle-plugin#137]
I have split for native libs in my app:

```groovy
splits {
    abi {
        enable true
        reset()
        include 'armeabi', 'x86', 'x86_64'
        universalApk false
    }
}
```

When I'm trying to assemble specific task, dex count is not executed, i.e.:
```bash
$ gradlew assembleArmeabiRelease
```

However it is working fine when I call 
```bash
$ gradlew assembleRelease
```
but now it also going to assemble 2 other apk's, which would be great to avoid doing.

**Comment by benjamin-bader** [comment]
Thanks for reporting - I'll look into it tomorrow morning.

**Comment by fcduarte** [comment]
@benjamin-bader your plugin is really great but with newer changes from the Android build tools team it's really broken for ABI splits.

Newer versions of Android Studio -- 2.2.3 as the time of writing -- will only build the target ABI apk for the connected device when you click run, take a look here: https://code.google.com/p/android/issues/detail?id=221098#c20

So here's what will happen:

````
:app:countDevDebugDevArm64-v8aDebugDexMethods FAILED
:app:countDevDebugDevArmeabi-v7aDebugDexMethods FAILED
:app:countDevDebugDevUniversalDebugDexMethods
Total methods in app-5.0-dev-universal-debug.apk: 90343 (137.85% used)
Total fields in app-5.0-dev-universal-debug.apk:  46794 (71.40% used)
Methods remaining in app-5.0-dev-universal-debug.apk: 0
Fields remaining in app-5.0-dev-universal-debug.apk:  18741

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:countDevDebugDevArm64-v8aDebugDexMethods'.
> java.io.FileNotFoundException: /Users/<obfuscated>/app/build/outputs/apk/app-5.0-dev-arm64-v8a-debug.apk (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:countDevDebugDevArmeabi-v7aDebugDexMethods'.
> java.io.FileNotFoundException: /Users/<obfuscated>/app/build/outputs/apk/app-5.0-dev-armeabi-v7a-debug.apk (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
==============================================================================
````

**Comment by benjamin-bader** [comment]
Hm, I knew that it didn't work properly with splits but I haven't seen _this_ kind of failure before!

Thanks for reporting, and for the detailed repro steps; I'll have time to investigate in a few more days.

**Comment by fcduarte** [comment]
Thanks @benjamin-bader for taking a looking at it. As a first attempt to fix I did #139, please take a look. Checking here on my end I don't have the error anymore but the plugin show the APKs that were not generated as 0 / 0%.

**Comment by benjamin-bader** [comment]
Is this still an issue, or did the linked PR fully address it?

**Comment by benjamin-bader** [comment]
I'll assume this is resolved.
