### ISSUE TITLE
methods counts error

### ISSUE THREAD

**Issue by aliang5820** [KeepSafe/dexcount-gradle-plugin#138]
:app:mergeDevDebugJniLibFolders UP-TO-DATE
:app:transformNative_libsWithMergeJniLibsForDevDebug UP-TO-DATE
:app:processDevDebugJavaRes UP-TO-DATE
:app:transformResourcesWithMergeJavaResForDevDebug UP-TO-DATE
:app:validateSigningDevDebug
:app:packageDevDebug
:app:assembleDevDebug
:app:countDevDebugDexMethods
Total methods in sign-debug-dev.apk: 66068 (100.81% used)
Total fields in sign-debug-dev.apk:  36813 (56.17% used)
Methods remaining in sign-debug-dev.apk: 0
Fields remaining in sign-debug-dev.apk:  28722

why used 100.81%

**Comment by aliang5820** [comment]
version:0.6.1

**Comment by aliang5820** [comment]
the reason is my methods more than 65536?

**Comment by benjamin-bader** [comment]
Presumably you're using multidex, correct?  It would allow you to have more than 0xFFFF methods.

I don't have a better idea for what to display when multidex is on; `100.81%` isn't so useful, but neither is dexcount if one has already set up multidex.

**Comment by aliang5820** [comment]
thx a lot
