### ISSUE TITLE
Failing when method number is exceeding

### ISSUE THREAD

**Issue by emartynov** [KeepSafe/dexcount-gradle-plugin#14]
Unfortunately I can not check it but I assume the plugin fails if methods number is bigger than 64k. Please confirm

**Comment by benjamin-bader** [comment]
Hi, the plugin won't fail, but it won't be invoked.  If your build exceeds the method limit, `dex` will fail, and the build will stop.  This happens before the plugin's task gets executed, as the plugin depends on the output of `dex`.

In other words, if you're over the limit, the plugin will not tell you by how much.

**Comment by emartynov** [comment]
Thank you!

**Comment by Erhannis** [comment]
Is there a way for it to do so?  I'm already over the limit, and I don't know by how much.

**Comment by benjamin-bader** [comment]
You could enable multidex, then build again.  We need an .apk or an .aar in order to tally up the methods; if you can't build one, then there's nothing we can do.
