### ISSUE TITLE
Use GradleTestKit for integration tests

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#141]
I've just discovered GradleTestKit, which lets you run Gradle builds as part of JUnit tests, including the plugins under development.  Our current integration tests are fragile and are not run as part of the usual `./gradlew check` development process; we should move them over to the Gradle test framework.

**Comment by jaredsburrows** [comment]
I have taken sometime to try the Gradle Test Kit in a separate project, I believe it is the better way to go when writing tests that use `build.gradle` files. See here: https://github.com/jaredsburrows/gradle-license-plugin/pull/33. I will help us migrate soon.

**Comment by jaredsburrows** [comment]
After reviewing this, for this project, it is easier to have test dependencies and test apks with our current tests now. Migrating to a new test framework might not be worth all of the code rewriting. I vote to close this issue. Let me know what you think.

**Comment by benjamin-bader** [comment]
SGTM
