### ISSUE TITLE
SdkResolver creates local.properties file, but without ndk_dir which leads to problems compiling project in some situations

### ISSUE THREAD

**Issue by shtolik** [KeepSafe/dexcount-gradle-plugin#144]
I've got problem building my project in jenkins, because of a problem described in details [here ](https://code.google.com/p/android/issues/detail?id=212688), which boils down to having `local.properties` file present that does not define the `ndk.dir` property — even if a valid `ANDROID_NDK_HOME` environment variable is set.
And I found out that in my case this local.properties files is generated by SdkResolver in dexcount-gradle-plugin:

```
22:01:58.569 [DEBUG] [com.getkeepsafe.dexcount.sdkresolver.SdkResolver] Missing local.properties.
22:01:58.570 [DEBUG] [com.getkeepsafe.dexcount.sdkresolver.SdkResolver] Found ANDROID_HOME at '/opt/in4mo/android/android-sdk-linux'. Writing to local.properties.
```
 So I can of course fix it by disabling plugin, or by manually modifying file (and doing it again every time after jenkins workspace is cleaned). But I hope it possible to make creation of local.properties file configurable (is it really needed by dexcount plugin?), or SdkResolver should also add ndk_dir into local.properties based on environment variable ANDROID_NDK_HOME=/opt/in4mo/android-ndk-r13b.

**Comment by benjamin-bader** [comment]
Thanks for reporting the issue; as you suggest, it seems reasonable for `SdkResolver` to add `ndk.dir` to the generated props file.  The file itself is used by the `dx` tool, on which we rely to counting `.aar` files.

I'd be happy to take a PR!
