### ISSUE TITLE
[Feature Request] Fail build on "maxMethodCount"

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#146]
## Question:
Can we add an integer such as "maxMethodCount" to the `https://github.com/KeepSafe/dexcount-gradle-plugin/blob/master/src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy` in order to fail builds that go over a certain number of methods?

## Example:
```groovy
dexcount {
  maxMethodCount = 580000
}
```

This will help developers that are developing on their local machines not only make better decisions on the code that they write but the libraries they use.

**Comment by benjamin-bader** [comment]
Sounds reasonable, but I'm afraid I don't have much time for new dexcount features lately.  I might get around to it at some point in the future, but if I see a PR for this beforehand, then so much the better!

If we were to start enforcing build failures, a related feature might be "method budgets", i.e. a build can only increase the count over the prior build by X methods, or else it triggers a failure.  Maybe that makes more sense as a build step in Jenkins, but it would be neat.

**Comment by jaredsburrows** [comment]
@benjamin-bader I would like to work on this. The idea is if a build hits the max "580000", it will just abort by throwing an exception.

**Comment by benjamin-bader** [comment]
Sounds good to me!

**Comment by vanniktech** [comment]
Should those be splitted up so one can set the max count for debug and release separately?

**Comment by jaredsburrows** [comment]
Based on how the current plugin works now(https://github.com/KeepSafe/dexcount-gradle-plugin#configuration), it does not check variants and since https://github.com/KeepSafe/dexcount-gradle-plugin/blob/master/src/main/groovy/com/getkeepsafe/dexcount/DexMethodCountExtension.groovy, does not iterate over each build variant, I believe it makes to since have 1 "maxMethodCount". If you want support for `debug` and `release`, it would only make sense to add support for "all variants". Other users that use this plugin may want support for extra `buildTypes`/`productFlavors`. This may force us to then create a "maxMethodCount" for each build variant.

Developers that way to use it in their `build.gradle` files simply need to add a check:
```
dexcount {

  if (release) maxMethodCount = 580000
}
```

**Comment by vanniktech** [comment]
The dynamic approach does not seem to work for me. Is there something I'm doing wrong?

```gradle
apply plugin: 'com.getkeepsafe.dexcount'

android.applicationVariants.all {
  if ("release" == it.buildType.name) {
    dexcount.maxMethodCount = 15000
  } else {
    dexcount.maxMethodCount = 58000
  }
}

android {
  // Usual configuration.
}
```

> The current APK has 53564 methods, the current max is: 15000.

**Comment by vanniktech** [comment]
The function gets called either way with both debug / release.

**Comment by benjamin-bader** [comment]
Right, so I assumed.  When you said "The dynamic approach does not seem to work for me", and posted an error about the current max being 15000, I assumed you intended a non-release build, and were surprised by the release configuration taking effect.  Did I misunderstand the issue?  If so, what is it you are trying to do?

**Comment by benjamin-bader** [comment]
Is it the case that all variants are being instantiated, but only some are subsequently built?  I suppose then that "release" is being instantiated after "debug".

**Comment by vanniktech** [comment]
Could be the case.
