### ISSUE TITLE
Language clean up + Add Kotlin support

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#150]
Can we look into cleaning up the code?
 - Adding documentation
 - Removing `Java` code from the `Groovy` `src/groovy` folder - https://github.com/KeepSafe/dexcount-gradle-plugin/pull/152

Also, have we considered looking into kotlin?

**Comment by xiphirx** [comment]
Is the kotlin plugin support good enough to use yet? If so, I'm all for using kotlin, groovy sucks.

**Comment by jaredsburrows** [comment]
@xiphirx I will look into it and report back.

**Comment by benjamin-bader** [comment]
Kotlin should just work - the Gradle and ABT APIs are all just Java.  Our Groovy code is also basically just Java-with-closures, so porting shouldn't hit any significant barriers.
