### ISSUE TITLE
Error:Could not set unknown property 'maxMethodCount' for object of type com.getkeepsafe.dexcount.DexMethodCountExtension.

### ISSUE THREAD

**Issue by jp1017** [KeepSafe/dexcount-gradle-plugin#154]
v0.6.2
as2.3.0
gradle3.4.1

**Comment by benjamin-bader** [comment]
Yep, let me cut a point release, will do momentarily.

**Comment by benjamin-bader** [comment]
I just pushed 0.6.3 to Maven Central, and it should be available within 10-15 minutes; `maxMethodCount` is included therein.

**Comment by jp1017** [comment]
@jaredsburrows @benjamin-bader Thanks, V0.6.3 works well. :smile:
