### ISSUE TITLE
Multi-APK apps

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#163]
What to do?

I guess this is the general case of Instant Apps.  Should we:
a) break out counts by APK?
b) break out counts by individual .dex files?
c) not count them at all because the dex limit is not so meaningful given multiple APKs?

**Comment by benjamin-bader** [comment]
#166, which brings support for the new build tools 3.0 versions, pushes ever-so-slightly in this direction by accepting an `@InputDirectory` as its task input.  It still just takes the first APK in that directory - we would still need some significant refactoring to handle more than one.

It's still not clear *what* we should do, though.  Let's defer action here until folks hit solid use-cases.

**Comment by sdoward** [comment]
**Use-case:** View the dex count for an instant app module using the `com.android.instantapp` plugin

I get the following error with version 0.7.3
`Dexcount plugin requires the Android plugin to be configured`

**Comment by benjamin-bader** [comment]
Interesting; I suppose it makes sense that there's a separate plugin for instant apps.  We have a whitelist of "expected" Android plugins, which does not currently include `com.android.instantapp`.  I'm not sure yet how we might fit it in - could be drop-in, or it could be impossible.  I'll investigate.

Thanks for the report!

**Comment by sdoward** [comment]
The instant app plugin produces a zip which may contain multiple apks (one for each instant app). Each APK cannot be above 64k methods so this plugin will probably be pretty important for those users. 

There is also `com.android.feature`. Which outputs both an APK for the instant app (which the `com.android.instantapp` consumes) and an aar which the main app consumes. It might be useful for the plugin to work with the `com.android.feature`. In this case is should get the dex count from the apk and ignore the aar.

**Comment by benjamin-bader** [comment]
Thanks for reminding me of this issue - got pretty busy over the last month and forgot to investigate.  I looked a bit last night - it's going to be a bit of work, because the InstantAppPlugin seems to do output quite differently from the others.  The plugin needs a large refactor to account for it.

It might be easier to just do the feature subprojects only, since (if I understand correctly) their outputs end up as part of the big zip at the end of the build.  Even so, the way forward isn't totally clear; this probably won't be done for the next release.

**Comment by jda-tid** [comment]
Any news on this feature? It would be great to include `com.android.instantapp` and `com.android.feature` as supported plugins

**Comment by benjamin-bader** [comment]
It would be great, but there's no news.  I'm not able to dedicate any time to implementing it, but would be happy to take a PR.

**Comment by benjamin-bader** [comment]
There's no trace of Instant Apps in the new Android Gradle Plugin API being released in v4.1.0.  I can see where it might happen in the future, but until such time as they provide a supported way to get the artifacts, I'm going to consider this "wontfix".
