### ISSUE TITLE
Unable to build/run plugin with Gradle 4.0 milestone 1

### ISSUE THREAD

**Issue by brandoFS** [KeepSafe/dexcount-gradle-plugin#165]
Just upgraded to android studio 3.0 and gradle plugin 4.0 milestone 1

getting the following error when trying to build

Error:Execution failed for task ':app:countStagingDebugDexMethods'.
> getMainOutputFile is no longer supported.  Use getOutputFileName if you need to determine the file name of the output.

**Comment by benjamin-bader** [comment]
Duplicate of #161, fix coming very soon - thanks for your patience!
