### ISSUE TITLE
Heads up on 3.0.0-alpha3 dependency

### ISSUE THREAD

**Issue by robertoestivill** [KeepSafe/dexcount-gradle-plugin#169]
Due to the following bug
https://issuetracker.google.com/issues/62331750
Using the snapshot version that depends on `com.android.tools.build:gradle3.0.0-alpha3` might break your builds.

**Comment by benjamin-bader** [comment]
Oh hey, that's an interesting bug.  I'm not sure that it applies to plugins; we primarily just consume data from the built tools' public API - using `dexcount` _shouldn't_ cause your project's unit tests to fail - as far as I know we can't force your project to be built using newer build tools.  I might be wrong though!

I'll look a little more closely at this soon.  Thanks!

**Comment by robertoestivill** [comment]
For some reason it does. I don't know if having this dependency actually overrides the original declaration, or what exactly is going on. 
I can confirm that if you have this plugin added when configured `3.0.0-alpha2`, then  `./gradlew test` fails , and works again when remove the plugin declaration.

**Comment by benjamin-bader** [comment]
Ugh, that's unfortunate.  Thanks for confirming!

It's _might_ be possible to support 3.0+ without explicitly depending on it; I'll investigate.

**Comment by benjamin-bader** [comment]
The latest 0.7.0-SNAPSHOT build should fix this; please let me know if it doesn't.

**Comment by robertoestivill** [comment]
```
...I wonder how many projects have had their build tools hijacked by this plugin, and never realized it?
```

@benjamin-bader that's a really good question. Probably just luck that newer build tools didn't brake anything. 

Glad to see the new snapshot, will try it when I have a chance.
