### ISSUE TITLE
Misleading README?

### ISSUE THREAD

**Issue by LouisCAD** [KeepSafe/dexcount-gradle-plugin#170]
Hi,

the readme talks about counting methods in "APK", but according to [this StackOverflow response](https://stackoverflow.com/questions/44414119/how-to-count-methods-in-a-kotlin-library/44414601#44414601), it works for libraries too, which are not apks.

The README should, in the first lines state clearly that is works for both libraries and apps

**Comment by benjamin-bader** [comment]
That's a good point - the readme hasn't been updated in a long time.  Care to make a PR?

**Comment by benjamin-bader** [comment]
Fixed as of 0.7.0.

**Comment by LouisCAD** [comment]
Thanks for updating the README, this is clearer now. Can you update the repo tagline to be the same of the first line of the updated README?
Updated README:
`A Gradle plugin to report the number of method references in your APK or AAR on every build.`
Old tagline:
`A Gradle plugin to report the number of method references in your APK on every build.`

I guess I can't make a PR for the tagline since it's not part of the repo content, but is only a property of the GitHub project.
