### ISSUE TITLE
What does the field count actually counts?

### ISSUE THREAD

**Issue by nemanja-galore** [KeepSafe/dexcount-gradle-plugin#171]
Hi,
I've been using the plugin for a while now and I love it! Keep up the good work.

Anyway, I'm careful to keep my project under 64k methods and so far I've been successful, but looks like I have hit another dex limit, the one about string literals. I know there is a limit on methods and a limit on string literals. When you guys say "fields" are you talking about string literals? What are you actually counting for fields?

The reason I'm asking is I no longer can build my project without `jumboMode=true` option. That leads me to believe a dex limit on strings has been hit. At the same time output of dexcount-gradle-plugin shows ~37k of fields.

If I run the following command on my apk
`jar xvf myapp.apk classes.dex && hexdump -s 56 -n 4 -e '1/4 "%d\n"' classes.dex`
the result is 65800 and that's in line with build fails and `jumboMode=true` fixing things. I'm not exactly sure what this command does but it should count the strings from the dex file.

**Comment by benjamin-bader** [comment]
We aren't counting strings - "fields" refers to actual field definitions in classes, like `private int mMyInt;`.  It's pretty unusual to exceed 65536 entries in a the string table (most folks hit the method limit first), so we haven't counted those yet.

If `jumboMode` fixes your build, then you've certainly exceeded 65536 strings.  The command you pasted seems reasonable; I can't tell just by looking, but it's very close to the command you'd use to count methods in a single .dex and the number seems right.

**Comment by nemanja-galore** [comment]
Yeah, I never expected to exceed 64k worth of strings, there is no logical explanation for this at the moment. I'll keep looking, thanks for your help.
