### ISSUE TITLE
exportAsCSV issue

### ISSUE THREAD

**Issue by cpeppas** [KeepSafe/dexcount-gradle-plugin#18]
I am getting the following error when using any of the configurations below

dexcount{
    includeFieldCount = true
    exportAsCSV = true
}
or 
dexcount{
    exportAsCSV = true
}

Error:(98, 0) No such property: exportAsCSV for class: com.getkeepsafe.dexcount.DexMethodCountExtension_Decorated
<a href="openFile:/Users/peppach/codebase/DLBi/employees-app-android/app/build.gradle">Open File</a>

I am using com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.2.1
and com.android.tools.build:gradle:1.4.0-beta3

**Comment by vanniktech** [comment]
The exportAsCSV functionality is only available in the 0.2.2-SNAPSHOT for now. So you have to either wait for a stable version or upgrade your version to SNAPSHOT.

**Comment by cpeppas** [comment]
cool thanks for letting me know
