### ISSUE TITLE
Dexcount doesn't produce any output

### ISSUE THREAD

**Issue by PiotrBandurski** [KeepSafe/dexcount-gradle-plugin#186]
Hi all!
I use last version of dexcount on my new Android project and I can't see any output from plugin in my `outputs/` folder. Also  `./gradlew assembleDebug` produces me only this output: 
<img width="332" alt="screen shot 2017-07-02 at 21 27 27" src="https://user-images.githubusercontent.com/12571316/27772965-b476ee58-5f6d-11e7-9163-edd780904620.png">
My build.gradle (app)
looks like that:

```
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply from: '../versioning.gradle'
apply plugin: 'realm-android'
apply plugin: 'com.getkeepsafe.dexcount'


buildscript {
    repositories {
        jcenter()
        maven {
            url 'https://maven.fabric.io/public'
        }
    }

    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'io.fabric.tools:gradle:1.+'
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.7.1'

    }
}
....
```
What I'm doing wrong?

**Comment by benjamin-bader** [comment]
Thanks for the bug report.  I can't tell what's going wrong.  Would you please clean your build, then run `./gradlew --debug assembleDebug > debug.log` and put it in a pastebin/gist/etc?

**Comment by benjamin-bader** [comment]
Also, what version of Android Build Tools are you using?

**Comment by jp1017** [comment]
@PiotrBandurski where are this:  :sob: 
```
dexcount {
    format = "list"
    includeClasses = false
    includeClassCount = false
    includeFieldCount = true
    includeTotalMethodCount = false
    orderByMethodCount = false
    verbose = false
    maxTreeDepth = Integer.MAX_VALUE
    teamCityIntegration = false
    teamCitySlug = null
    runOnEachPackage = true
    maxMethodCount = 64000
}
```

**Comment by PiotrBandurski** [comment]
@jp1017 also in build.gradle (app)
@benjamin-bader I'm using com.android.tools.build:gradle:2.3.3 and gradle-3.3.
Here is my log:

[debug.txt](https://github.com/KeepSafe/dexcount-gradle-plugin/files/1118497/debug.txt)

**Comment by benjamin-bader** [comment]
Thanks for the build log.  Sadly, it doesn't contain any obvious problem.

One thing I notice is that the dexcount task is definitely being run, but it finishes _really_ quickly - so quickly, that I wonder if it just can't find your APK.  Are you possibly moving or renaming the APK file in a `doLast` block or something?

**Comment by jp1017** [comment]
@PiotrBandurski  So, can you show us the full build.gradle config. :smile: 
Secondly, can this worked in other project. 
Thirdly, can you show us the demo to make this issue?

**Comment by PiotrBandurski** [comment]
@benjamin-bader That was it... I had a `doLast` in my build gradle and this was causing problem with method counting. Thanks for help!

**Comment by benjamin-bader** [comment]
Great - glad to hear it's working now!
