### ISSUE TITLE
Could not Get 

### ISSUE THREAD

**Issue by adymilk** [KeepSafe/dexcount-gradle-plugin#203]
When I build myapp use android studio. It says  Could not resolve all dependencies for configuration ':classpath'. > Could not resolve com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.6.4. Required by: project : ......
What's wrong？please

**Comment by benjamin-bader** [comment]
Show me the `buildscript` section of your root `build.gradle` file?

**Comment by jaredsburrows** [comment]
@adymilk Can you please post your `build.gradle`?

**Comment by kawnayeen** [comment]
Hi, you need to add the dependency into your project build.gradle.

**Comment by benjamin-bader** [comment]
Since I haven't heard from you, I'm assuming that either the problem is resolved, or you've moved on to another solution.  I'll close this issue for now; please feel free to open a new issue if you find another problem with dexcount.
