### ISSUE TITLE
Plugin with id 'com.getkeepsafe.dexcount' not found

### ISSUE THREAD

**Issue by macaronlover** [KeepSafe/dexcount-gradle-plugin#204]
Just try to implement Dexcount plugin within my project, but for some reason is not working and I get the following error (details are below):

> Plugin with id 'com.getkeepsafe.dexcount' not found

**Code**
```
apply plugin: 'com.android.application'
apply plugin: 'com.getkeepsafe.dexcount'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.0"
    defaultConfig {
        applicationId "com.packagename.customtoolbarwithsupportlibrary"
        minSdkVersion 21
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.7.3'
    compile 'com.android.support:appcompat-v7:25.0.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}
```

![screen shot 2017-07-30 at 20 22 37](https://user-images.githubusercontent.com/12353505/28756375-dd6dfaba-7564-11e7-90c6-fc18a028b4c7.png)

![screen shot 2017-07-30 at 20 15 20](https://user-images.githubusercontent.com/12353505/28756351-77bc4ff0-7564-11e7-870e-ab2d738d32b9.png)

**Comment by benjamin-bader** [comment]
Your classpath dependency is in the wrong place.  It needs to be part of your `buildscript` dependencies, as shown in the example in the readme.

**Comment by macaronlover** [comment]
Still get an error after doing that:
> Dexcount plugin requires the Android plugin to be configured

**Comment by benjamin-bader** [comment]
That's because you need to apply the Android plugin _before_ the dexcount plugin:

```
apply plugin: 'com.android.application'
apply plugin: 'com.getkeepsafe.dexcount'
```

**Comment by macaronlover** [comment]
K

> Error:Cause: buildToolsVersion is not specified

```
apply plugin: 'com.android.application'
apply plugin: 'com.getkeepsafe.dexcount'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'

        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.7.3'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}
```

![screen shot 2017-07-31 at 12 18 23](https://user-images.githubusercontent.com/12353505/28775524-63592c3c-75ea-11e7-9039-882949da8cfe.png)

**Comment by benjamin-bader** [comment]
This error is entirely unrelated to dexcount.  At this point, I'd suggest taking your questions to stackoverflow.com.
