### ISSUE TITLE
[Feature Request] - Do not run the count on each build

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#208]
Add an option to the plugin's extension to prevent it from counting after each `assembleDebug`.

**Comment by benjamin-bader** [comment]
`runOnEachAssemble = false` in the dexcount config should do this, no?

**Comment by jaredsburrows** [comment]
@benjamin-bader 
According to the readme:
```
runOnEachPackage: When false, does not run count method during package task. True by default. Synonym for runOnEachAssemble, which is deprecated.
```
So I should use `runOnEachPackage` and not `runOnEachAssemble`? But `runOnEachAssemble` is now deprecated?

**Comment by benjamin-bader** [comment]
Oh yeah, that's right - `runOnEachPackage` is the thing you want.  Forgot about that!  They do the same thing.

**Comment by jaredsburrows** [comment]
Thanks. Maybe I will update the docs on README.md later.
