### ISSUE TITLE
[Feature] Summary count tasks

### ISSUE THREAD

**Issue by vanniktech** [KeepSafe/dexcount-gradle-plugin#21]
Let's say I have one project with 2 flavors, hence I'll get those tasks:

```
count<Project><Flavor1>DebugDexMethods
count<Project><Flavor1>ReleaseDexMethods
count<Project><Flavor2>DebugDexMethods
count<Project><Flavor2>ReleaseDexMethods
```

Would not it be also cool to have:

`count<Project><Flavor>DexMethodsAll` which will execute:
 `count<Project><Flavor>DebugDexMethods` and `count<Project><Flavor>ReleaseDexMethods`

And also:

`count<Project>DexMethodsAll` which will execute:
`count<Project><Flavor1>DebugDexMethods`, `count<Project><Flavor1>ReleaseDexMethods`, `count<Project><Flavor2>DebugDexMethods` and `count<Project><Flavor2>ReleaseDexMethods`

The problem that I have is that the `build` Task takes about 45 minutes to build all of my projects since there are quite a lot Therefore I have two Jenkins tasks. One that executes `build` and the other ones that executes `check`. In order to get the dexcount also in the `check` Jenkins Job I'd need to chain all of the `count` tasks.

**Comment by benjamin-bader** [comment]
Right now you could do single-flavor counts by doing `./gradlew assembleFlavor1Release`, which would build and dex just that one flavor - I'm actually in your same boat (with NDK plus multiple flavors), so that's what I do.

The way it currently works, the count task's name and existence is predicated entirely on what variants are being assembled.  Can you just update the counts directly from the `build` job?

**Comment by vanniktech** [comment]
I figured out yesterday that those summary tasks don't really help. I had the assumption that the count tasks depend on something other than the actual APK(s). Since the `check` Jenkins Job never actually builds APKs those summary tasks are useless.

I guess your solution of using `./gradlew assembleFlavor1Release` is best. Maybe I'll just do another Jenkins Build that only plots the dexcounts and does nothing else as that would not take that long since Unit Tests and all of the static analyze tools won't run. Also an incremental build for that Jenkins task would be an option in order to speed up the build process.

**Comment by benjamin-bader** [comment]
As it doesn't seem that there is anything to do, I'm closing this issue.
