### ISSUE TITLE
Plugin doesn't work when outputFileName was changed

### ISSUE THREAD

**Issue by LPFinch** [KeepSafe/dexcount-gradle-plugin#233]
I have error when i change AAR output name in build.gradle
```java
android.libraryVariants.all { variant ->
        variant.outputs.all {
            outputFileName = "${name}-${version}.aar"
        }
    }
```

Error log
```java
Error:A problem was found with the configuration of task ':sdk:countReleaseDexMethods'.
> File 'PATH_TO_AAR_WITH_ORIGINAL_NAME' specified for property 'inputFile' does not exist.
```

P.S.
Original name looks like name-release.aar

**Comment by benjamin-bader** [comment]
Hi, I've just pushed a new build (version 0.8.2) to Maven Central, which ought to address this bug.  It will be available within the next 5 minutes; please let me know whether it solves your problem.

**Comment by benjamin-bader** [comment]
Hi @LPFinch, have you had a chance to try the new version yet?  Please let me know if you're still hitting this bug.

**Comment by LPFinch** [comment]
@benjamin-bader sorry for delay, works like a charm. 
Thank you

**Comment by benjamin-bader** [comment]
Great, thank you!
