### ISSUE TITLE
Difference between "Total methods" and "Methods remaining" ?

### ISSUE THREAD

**Issue by rafoufoun** [KeepSafe/dexcount-gradle-plugin#244]
Hello, 

I have a question about the output of this plugin :    

What's the difference between the "Total methods in apk" count and the "Methods remaining in apk" ?
  
My release apk is proguarded, so I was expecting that if a method is not used, it will not be counted in the total methods count.

Thanks

**Comment by benjamin-bader** [comment]
"Total methods in APK" is the total number of method references in your APK.
"Methods remaining in APK" is just `65336 - totalMethods` - in other words, how many more method references you can fit in your app without multidex.

**Comment by benjamin-bader** [comment]
I'm guessing that there's no further issue here, so I'll close this one out.  Please feel free to re-open if you have any more problems.
