### ISSUE TITLE
Plugin doesn't recognise APKs with a DEX_FILE_MAGIC value of 038

### ISSUE THREAD

**Issue by fractalwrench** [KeepSafe/dexcount-gradle-plugin#247]
Android 8.0 incremented the `DEX_FILE_MAGIC` constant from 037 to [038](https://source.android.com/devices/tech/dalvik/dex-format#dex-file-magic). The plugin appears to only allow Dex files whose value is 035 or 037, which is [enforced with this check](https://github.com/KeepSafe/dexcount-gradle-plugin/blob/129444243c2a38c195283eeda7724360b10677f0/src/main/java/com/android/dexdeps/DexData.java#L70).

This prevents the method count from being calculated by the plugin - at least in a sample Hello World app targeting API 28, on Android Studio 3.2 Canary.

I _think_ that the fix to this would be to simply expand the check to include 038. I can give a go at creating a PR if you're happy with this approach?

**Comment by benjamin-bader** [comment]
Thanks!  That's the same approach we've taken in the past - please feel free to send a PR.

**Comment by benjamin-bader** [comment]
I've just pushed version 0.8.3 to Maven Central, which contains this fix.  It should be available within the next 15-30 minutes.

Thanks again for contributing!
