### ISSUE TITLE
Not compatible with Android App bundle

### ISSUE THREAD

**Issue by riyaz** [KeepSafe/dexcount-gradle-plugin#250]
Dexcount does not seems to work with `bundle` variant of Android App Bundle, to make app bundle we build with bundle task then assemble i.e instead of assembleRelease it would be bundleRelease, for android app bundle assemble is no longer required or used.

I suppose we need to hook the dexcount plugin to bundle task too?

**Comment by benjamin-bader** [comment]
That sounds reasonable - but I've never worked with bundles, either, so I wonder if there isn't going to be more to the story than that.  It's a good place to start!

**Comment by riyaz** [comment]
Trying android app bundle is easy, 

1. Bump the gradle tools version to com.android.tools.build:gradle:3.2.0-beta02
2. enable aapt2 android.enableAapt2=true

After above 2, you will be able to find bundle* tasks, I will see if i can send PR, do i need to add bundle here https://github.com/KeepSafe/dexcount-gradle-plugin/blob/master/src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt#L226

**Comment by benjamin-bader** [comment]
Sure it's easy, I just haven't done it :)

I'm not working on Android apps day-to-day at the moment, and don't really have time outside of work right now.  I'd be grateful & happy to accept a PR!

**Comment by yevhenii-kanivets** [comment]
As a workaround with CI, you always can use `./gradlew countReleaseDexMethods` as an additional step.
