### ISSUE TITLE
plugins { id("xxx") } 

### ISSUE THREAD

**Issue by jmfayard** [KeepSafe/dexcount-gradle-plugin#256]
Is there a way to use the new plugins syntax instead of bulidscript? 

That makes for a much better user experience when working with the gradle kotlin dsl. 

```
plugins {
    id «plugin id» version «plugin version»
}
```

See the information `about the new plugin mechanism` in this page

https://plugins.gradle.org/plugin/jmfayard.github.io.gradle-kotlin-dsl-libs

https://plugins.gradle.org/docs/submit

**Comment by benjamin-bader** [comment]
Wow, that was a really frustrating process!  I just attempted to publish at plugins.gradle.org; we are "pending approval".  This is an improvement over the last time I tried this, when the publishing plugin crashed in the presence of signature files (a requirement for Maven Central).

Perhaps soon, you'll be able to use the new plugin syntax.

**Comment by jmfayard** [comment]
@benjamin-bader 
yes they have a manual validation to check that you put the right url to github and things like that
you can email eric at gradle.com to get validated

**Comment by benjamin-bader** [comment]
Thanks for the intro; plugin is approved.  Please confirm whether you can use it.

**Comment by jmfayard** [comment]
Unfortunately, it doesn't 

https://github.com/jmfayard/okAndroid/commit/fd9bd8312823ff7bfe6603d36f9dad052c0a20d9

```
Build file '/Users/jmfayard/Dev/mautinoa/okAndroid/ok/build.gradle.kts' line: 8

* What went wrong:
An exception occurred applying plugin request [id: 'com.getkeepsafe.dexcount', version: '0.8.4']
> Failed to apply plugin [id 'com.getkeepsafe.dexcount']
   > Dexcount plugin requires the Android plugin to be configured
```

It could have something to do with https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/#declarative-scripts

**Comment by benjamin-bader** [comment]
Ah, now _that's_ a familiar error!  You have to apply the `com.android.application` plugin before applying dexcount.  I think you can put that in the `plugins` block, too, and it should work.

**Comment by jmfayard** [comment]
@benjamin-bader I can confirm it works!

**Comment by jmfayard** [comment]
@benjamin-bader 

Actually yes it's work, but it's not super straight-forward

For someone having a look at this issue, this is how you have to do it like this

```kotlin
// app/build.gradle.kts
plugins {
    id("com.android.application")
    id("com.getkeepsafe.dexcount")
}

// but also add to the classpath because google didn't bother to publish the necessary artifacts for the android gradle plugin
// build.gradle.kts
buildscript {

    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath("com.android.tools.build:gradle:3.2.0")
        classpath("com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.8.3")
    }
}
```



```

**Comment by benjamin-bader** [comment]
Ouch, that's too bad about Google not publishing to plugins.gradle.org!  Thanks for confirming.  Can we consider this issue to be resolved?

**Comment by jmfayard** [comment]
Yes!
