### ISSUE TITLE
Provide Gradle Kotlin DSL examples in documentation

### ISSUE THREAD

**Issue by eriwen** [KeepSafe/dexcount-gradle-plugin#258]
As a [Gradle Kotlin DSL](https://github.com/gradle/kotlin-dsl) adopter, I'd like to know how to configure this plugin using the Kotlin DSL.

[This plugin was identified](https://github.com/gradle/gradle/issues/6790) as one of the most useful Gradle plugins. With Kotlin DSL 1.0 approaching shortly, it'd be wonderful if the documentation provided Kotlin and Groovy DSL samples. [Blog post with suggestions](https://blog.gradle.org/groovy-kotlin-dsl-samples).

Here are a couple additional resources:

 * [Migrating build logic from Groovy to Kotlin guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/)
 * [Exemplar for automated samples testing](https://blog.gradle.org/documentation-samples-testing-exemplar)
 * [Join #kotlin-dsl channel in Gradle Community Slack for personalized help](https://join.slack.com/t/gradle-community/shared_invite/enQtNDE3MzAwNjkxMzY0LTYwMTk0MWUwN2FiMzIzOWM3MzBjYjMxNWYzMDE1NGIwOTJkMTQ2NDEzOGM2OWIzNmU1ZTk5MjVhYjFhMTI3MmE)

Thank you for providing a great Gradle plugin! —The Gradle Team

**Comment by benjamin-bader** [comment]
I'd be happy to take a PR here, but don't have much time these days to devote to this project, and it appears that this task would at the very least mean an hour or two of futzing around with build scripts and learning.

(not that I'm opposed to learning, just very short on time these days!)
