### ISSUE TITLE
Deploy version 0.3.0

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#26]
@ajalt would you please make a release based off of master, if you have time?  I'm no longer able to do this myself.

**Comment by ajalt** [comment]
Hmm... uploads aren't working for me through command line or the web interface right now. I'll try again tomorrow.

**Comment by jaredsburrows** [comment]
+1

**Comment by ajalt** [comment]
https://oss.sonatype.org/service/local/staging/deploy/maven2 is still returning 500 when I try to upload to it, and uploads through the web interface never complete. Any ideas?

**Comment by jaredsburrows** [comment]
Use jcenter

**Comment by benjamin-bader** [comment]
Sounds like a Sonatype problem; you can post a JIRA issue, Joel is pretty good about responding.  Probably he messed up your access when he removed mine.

**Comment by benjamin-bader** [comment]
I just thought of something else.  The build script expects credentials named `SONATYPE_NEXUS_USERNAME` and `SONATYPE_NEXUS_PASSWORD`.  This is different from MultiStateAnimation, which expects `NEXUS_USERNAME` and `NEXUS_PASSWORD`.

I set it up that way because I had a personal login already on my system with the shorter names.  You may not have the longer names configured - if not, there's no reason to keep the current config.

**Comment by ajalt** [comment]
Those variables weren't defined, but defining them in my system gradle.properties still results in a 401 response.

**Comment by benjamin-bader** [comment]
Assuming that those credentials are making it over the wire (squint at the `--verbose` output, grep for `Authorization`), then it is in fact a Sonatype problem.

@jaredsburrows I'd avoided jcenter when setting this project up for two reasons.  One, although they mirror Maven Central, I'm not sure that the reverse is true - meaning that jcenter distribution is potentially more limited in reach.  Two, I personally find their marketing/advocacy/evangelism to be less than honest so I'm just less inclined to trust them generally.

However.

Given the difficulty in making a release via Maven Central, it could be worth investigating.  They advertise themselves as an easier deploy target - whether or not that's actually true!

**Comment by ajalt** [comment]
The gradle output is pretty useless

```
12:26:20.803 [DEBUG] [sun.net.www.protocol.http.HttpURLConnection] sun.net.www.MessageHeader@22a4cd718 pairs: {null: HTTP/1.1 401 Unauthorized}{Date: Tue, 03 Nov 2015 20:26:20 GMT}{Server: nginx}{WWW-Authenticate: BASIC realm="Sonatype Nexus Repository Manager"}{X-Content-Type-Options: nosniff}{X-Frame-Options: SAMEORIGIN}{Content-Length: 0}{Connection: keep-alive}
```

I've got a ticket open, so I'll keep you updated.

I agree that bintray is shady, and I'd prefer to avoid them. When I did look into them for MultiStateAnimation, their deployment process wasn't even any easier. If you want to switch hosts, I'd recommend jitpack, since no deployments are necessary with them. If you decide to go that route, let me know and I'll create a pull request for it.

**Comment by ajalt** [comment]
Well, command line is still busted, and the support isn't able to help. Manual upload through the website is also still broken, but apparently only on firefox. I think I was able to do the upload manually with chrome.

**Comment by ihrthk** [comment]
+1

**Comment by benjamin-bader** [comment]
@ajalt Would it make sense for me to have permission to push releases myself?  I'd like to get this un-stuck, and at the same time feel bad putting it all on your shoulders.  If you think it makes sense, let's see what @philippb thinks.  I'm not sure how fine-grained we can get Sonatype permissions - it's a Joel question.  One option could be to have him create a sub-group `com.getkeepsafe.dexcount`, if possible.

**Comment by ajalt** [comment]
I wasn't clear enough in my last post, but I was able to upload 0.3.0 manually through the web interface, so you should be good to go for this release. I'll see about getting you push permissions for the future.

**Comment by benjamin-bader** [comment]
Oh, my mistake - I see it now.  Thanks for your help!
