### ISSUE TITLE
Print APK/AAR size next to method count

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#27]
It would be really nice for you to print the APK/AAR size next to the method count so we may see the difference.

**Comment by benjamin-bader** [comment]
I'm not sure that I understand what you mean.  Are you referring to the file size?  If so, that will be quite easy - I'd welcome a pull request for it.

The only caveat is that the file size should go on a separate line so as not to break people's existing integrations e.g. with CI jobs.

**Comment by xiphirx** [comment]
I believe a byte size of the actual code would be more beneficial here. That way auxiliary resources are left out of the picture.

**Comment by jaredsburrows** [comment]
@benjamin-bader @xiphirx Regardless, it would be nice to show the difference that code changes make.

For instance, naturally debug version would be larger than proguarded releases. I wanna see the classes.dex or APK size difference between them.

**Comment by vanniktech** [comment]
@jaredsburrows I had the same idea yesterday / today and hence I made this: https://github.com/vanniktech/gradle-android-apk-size-plugin

It'll basically just like this plugin jump into each assemble method and generate csv files for each output file and variant.

**Comment by jaredsburrows** [comment]
@vanniktech I have added the plugin to the classpath and the dependency to the dependencies block, it is not printing out anything.

Since you do not have any instructions, I had to do `gradle tasks`. I found the following:
```
sizeDebugApk
sizeDogfoodApk
sizeReleaseApk
```
Can you make it like the KeepSafe plugin and **always** print the size of the **APK**?

**Comment by benjamin-bader** [comment]
@vanniktech Thanks for sharing your plugin, it looks nice!  Since it meets the needs outlined in this issue, I'm going to close it.  It seems better to me to keep these functionalities separate.

**Comment by vanniktech** [comment]
Thanks. I'll work on those issues later. @benjamin-bader your plugin inspired mine ;)
