### ISSUE TITLE
don't have the dexcount output info or file

### ISSUE THREAD

**Issue by lijiankun24** [KeepSafe/dexcount-gradle-plugin#290]
I had added the dexcount-gradle-plugin 1.0.0 and applied the plugin，why don't have the dexcount output info or file？

**Comment by benjamin-bader** [comment]
That's a good question.  How are you running your build?

**Comment by lijiankun24** [comment]
execute ‘./gradlew assembleDebug’ command line

**Comment by benjamin-bader** [comment]
That should do it; it's what we do in our integration tests: https://github.com/KeepSafe/dexcount-gradle-plugin/blob/master/.buildscript/test.sh#L15

If you run with `--stacktrace --info`, do you see anything related to dexcount?  If so, what is it?

What version of Gradle are you using?  What version of the Android Gradle Plugin?

**Comment by lijiankun24** [comment]
“dexcount requires Gradle 5.1 or above”

I use 4.6 gradle and 3.2.0 Android Gradle Plugin.

**Comment by benjamin-bader** [comment]
That's it, then - to use dexcount, you'll need to upgrade your gradle version or downgrade your dexcount version.

I'd encourage you to upgrade Gradle - v5 brings some nice improvements, and (probably) won't require any code changes on your end.  Obviously that's your choice :)

**Comment by lijiankun24** [comment]
thank you :)
