### ISSUE TITLE
Doesn't work to windows

### ISSUE THREAD

**Issue by ViniciusGuardieiroSousa** [KeepSafe/dexcount-gradle-plugin#295]
Hi, when I build the project (I had followed  the tutorial on readme), on mac the plugin had worked
![image](https://user-images.githubusercontent.com/54741328/76092972-05cd4980-5f9f-11ea-8a0c-72dfb576ca6e.png)

**Comment by benjamin-bader** [comment]
Can you be more specific about what didn't work?  Do you have any build logs you can share?

**Comment by benjamin-bader** [comment]
Any update?  I'm happy to help but need to know what specifically didn't work.  Error messages, expected behavior that you didn't see, unexpected behavior that you _did_ see, all of that helps.

**Comment by ViniciusGuardieiroSousa** [comment]
I'm trying to redo the error, now I used a small Project and Works normally, tomorrow I'll set up on a larger Project and see if I have any errors.

On the first time, when I reported the error I was giving an IO excpetion, FIleNotFoundException and when built, the folders have been created but there were no files (index.html, style.css and others)

**Comment by benjamin-bader** [comment]
Thanks.  That makes me suspect that your build failed but the plugin still ran, or that your build was someplace we didn't expect.  Either way would be a bug.  If you're able to reproduce the problem, I'd be glad to know how.

**Comment by benjamin-bader** [comment]
Since I haven't heard back from you in two weeks, I'm going to close this.  Please feel free to re-open if and when you find a repro.
