### ISSUE TITLE
Consider depending on org.gradle.util.GradleVersion when it becomes public

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#308]
We have our own GradleVersion class because `org.gradle.util.GradleVersion` is technically an internal API.  According to https://github.com/gradle/gradle/issues/4884, this is slated to be made a public API in Gradle 6.6.

If/when that happens, let's evaluate whether we can use it.  As long as its public API remains compatible with its current internal one, we'll be good to depend on it.

**Comment by ZacSweers** [comment]
Why not use `VersionNumber` and just parse the gradle version string with that?

**Comment by benjamin-bader** [comment]
I don't remember if I ever knew about that class before, but it's news to me now!

It does seem to be public, which is nice.  I'll look at whether it's applicable here.  Thanks for the pointer!

**Comment by benjamin-bader** [comment]
Ah, right.  It's deprecated, naturally:
https://github.com/gradle/gradle/blob/master/subprojects/core/src/main/java/org/gradle/util/VersionNumber.java#L27

**Comment by benjamin-bader** [comment]
Somehow when I left that comment, I missed that on April 13 Gradle did in fact make `GradleVersion` public: https://github.com/gradle/gradle/pull/16809

Let's see what we can do here :)
