### ISSUE TITLE
[Feature] - includeClassCount

### ISSUE THREAD

**Issue by vanniktech** [KeepSafe/dexcount-gradle-plugin#36]
That would basically print out the total number of classes into the terminal plus the summary files.

**Comment by benjamin-bader** [comment]
Thanks for the suggestions!

I'm -1 on it, for two reasons.  First, while perhaps interesting to know, the number of classes doesn't really impact your build in any direct way, other than (usually) correlating with the number of methods.  Second, you can compute this from the dexcount output today, by configuring it to include per-class method counts and then filtering the output file.

**Comment by vanniktech** [comment]
The only real reason I wanted to have this one is so that I could also plot the number of classes in debug / release in Jenkins and see how much I can reduce or not reduce. 

But yeah # of classes does not impact the building of the apk.
