### ISSUE TITLE
The new count* tasks do not upload the Proguard mapping file to Crashlytics

### ISSUE THREAD

**Issue by ashughes** [KeepSafe/dexcount-gradle-plugin#364]
After updating to `2.0.0` our stacktraces were no longer being deobfuscated in Crashlytics. I finally discovered the reason was that the new `count[variant]DexMethods` and `count[variant]BundleDexMethods` tasks don't invoke the `uploadCrashlyticsMappingFile[variant]` task. I was able to figure this out by including `--profile` and looking at the Task Execution section.

I also ran a `--scan` to get more details about the tasks. This is when I discovered that the new `count*` tasks depend on the `minify*` and `sign*` tasks, while the "normal" `assemble*` and `bundle*` tasks depend on the `uploadCrashlyticsMappingFile*` task (which depends on the `minify*` task) and `sign*` task. See screenshots below.

<details>
<summary>Screenshot of bundle* task predecessors</summary>

![Screenshot from 2020-11-13 16-29-28](https://user-images.githubusercontent.com/295214/99133508-1d99aa80-25cf-11eb-9ec7-a35a7c7e2d2b.png)

</details>

<details>
<summary>Screenshot of dexcount tasks predecessors</summary>

![Screenshot from 2020-11-13 16-30-28](https://user-images.githubusercontent.com/295214/99133694-c8aa6400-25cf-11eb-94e7-2bd1bf859798.png)
![Screenshot from 2020-11-13 16-30-02](https://user-images.githubusercontent.com/295214/99133518-238f8b80-25cf-11eb-92b5-50f0d6fbdc78.png)

</details>

I took a peek at where these tasks are added [here](https://github.com/KeepSafe/dexcount-gradle-plugin/blob/4c6c666eed038ab376c4af5a92a8d07980d9c5b2/src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt#L448) and [here](https://github.com/KeepSafe/dexcount-gradle-plugin/blob/4c6c666eed038ab376c4af5a92a8d07980d9c5b2/src/main/kotlin/com/getkeepsafe/dexcount/Plugin.kt#L482) but I don't really understand enough about how the task dependencies work. I don't see anywhere where the new `count*` tasks (or rather the `generate[variant]PackageTree` tasks) explicitly depend on the `minify*` and `sign*` tasks, so I'm guessing that's not how it works. It *seems* to me that the `count*` tasks should just depend on the corresponding `assemble*` and `bundle*` task, which would then solve the problem, but again, I'm not sure if that's how it works.

It's unclear to me whether this is 100% an issue with the dexcount plugin or the Crashlytics plugin or a little of each. For example, is there something different the dexcount plugin could do to depend directly on the "normal" `assemble*` and `bundle*` tasks? Or should the Crashlytics plugin be injecting the `uploadCrashlyticsMappingFile*` appropriately so that the dexcount plugin would be invoking that instead of the `minify*` task?

As a workaround, I've found that the following works:
```
# Build an APK and count its method references
./gradlew assemble[variant] count[variant]DexMethods

# Build an AAB and count its method references
./gradlew bundle[variant] count[variant]BundleDexMethods
```
Doing this appears to only add the two additional dexcount tasks (`generate[variant]PackageTree` and `count[variant]DexMethods`) after the normal APK/AAB build process.

**Comment by benjamin-bader** [comment]
To be clear, dexcount-gradle-plugin has _never_ purported to run Crashlytics tasks, or any other plugin's tasks.  It seems like that may have been a side-effect of the fact that we relied on AGP's `package` tasks, which in turn depend on `assemble`, etc.

The new AGP APIs consider tasks to be private implementation details - they deal only in artifacts (APKs, AABs, etc), and whatever tasks are required to produce them is opaque to us.  We can't make any guarantee (or even any reasonable effort) about _which_ tasks are invoked.

So, sad to say, we can't help you with this.  If it's important to upload your mapping files and count your method references in the same Gradle invocation, please add `uploadCrashlyticsMappingFile` to your command line.
