### ISSUE TITLE
How to run the dex count  task in a special Build Variant???

### ISSUE THREAD

**Issue by snowdream** [KeepSafe/dexcount-gradle-plugin#37]
for  example, i just want to run the dex count task when i build with release, but not debug.
what can i do?

**Comment by snowdream** [comment]
It means,  i want to run the dex count task when i execute `gradle assembleRelease --info`, but not when i execute `gradle assembleDebug --info`

**Comment by benjamin-bader** [comment]
Interesting, I'm not sure!  The usual way for doing things only in this or that variant would be to configure that variant specially, but that won't work for this plugin.

My guess is that you'd need to have an `afterEvaluate` section in `build.gradle` where you found the `countDebugDexMethods` task and removed it from the task graph.  Maybe there's a simpler/less-fragile way, but that ought to get the job done.

Out of curiosity, what is the motivation?  Is there too much output when building with `--info`?

**Comment by snowdream** [comment]
i want to check more info with this option.
by the way, The dex task will cost much time? or not.

**Comment by benjamin-bader** [comment]
I don't have numbers, but the dexcount task does only a small amount of work compared to the other tasks; I've never noticed it taking much time.  The work is mainly just unzipping an .apk and reading headers from the classes.dex file inside.

**Comment by snowdream** [comment]
Got it,Thank you.@benjamin-bader
