### ISSUE TITLE
Release 0.3.1

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#39]
Hi @philippb,

Would you mind shipping the latest bits to Maven Central?  I've done everything up to, but I don't think I can push KeepSafe bits anymore.  AJ knows what to do.

This will fix #33 as well.

Thanks!

**Comment by ajalt** [comment]
@benjamin-bader You don't have to post it on here, but get me your sonatype username and I'll request publish permissions for it.

**Comment by benjamin-bader** [comment]
Thanks - sent you an email.

**Comment by ajalt** [comment]
Alright, you should have permissions now. Let me know if it still doesn't work.

**Comment by benjamin-bader** [comment]
Great!  Everything works.  Thanks again.
