### ISSUE TITLE
Release version with AGP 7.0 support.

### ISSUE THREAD

**Issue by nevack** [KeepSafe/dexcount-gradle-plugin#398]
For now we have to use `https://oss.sonatype.org/content/repositories/snapshots` repo with `2.1.0-SNAPSHOT` version.

**Comment by benjamin-bader** [comment]
When AGP 7.0 is officially released, then I'll do so.

**Comment by nevack** [comment]
It's up!
https://maven.google.com/web/index.html?q=gradle#com.android.tools.build:gradle-api:7.0.0
https://developer.android.com/reference/tools/gradle-api
https://developer.android.com/studio/releases/gradle-plugin#7-0-0

**Comment by benjamin-bader** [comment]
Yep!  Today's the day.  Just need to work out some related things (e.g. whether we need a new major version given the recent conversion from Kotlin to Java)

**Comment by benjamin-bader** [comment]
3.0.0-RC01 is live in Maven Central now.  Please give it a try and let me know what issues you hit, if any.  Thanks!

**Comment by benjamin-bader** [comment]
Err, please try *3.0.0-RC02*.  RC01 is busted.
