### ISSUE TITLE
More detailed dex count

### ISSUE THREAD

**Issue by ajma** [KeepSafe/dexcount-gradle-plugin#4]
Maybe borrow code from this to give a more detailed dex count:

https://github.com/mihaip/dex-method-counts

**Comment by benjamin-bader** [comment]
We currently write this output to a file, e.g. in `app/build/outputs/dexcount`.

**Comment by benjamin-bader** [comment]
Hi, did this file end up working for you, or should this issue stay open?

**Comment by ajma** [comment]
I haven't had a change to integrate this yet. I'll go ahead and close. I'll reopen if I need anything else.
