### ISSUE TITLE
Plugin Extensions property getters clash with fields when used in Groovy

### ISSUE THREAD

**Issue by nevack** [KeepSafe/dexcount-gradle-plugin#401]
![image](https://user-images.githubusercontent.com/8330119/127742659-5e6aba59-a294-43fe-9761-50bbc7731030.png)

**Comment by benjamin-bader** [comment]
How annoying.  Seems simple to fix, thankfully.

**Comment by benjamin-bader** [comment]
It's funny that Gradle itself doesn't complain at all about this.  Seems to me that this is likely to be an IntelliJ bug.
