### ISSUE TITLE
[Feature Request] Allow Dexcount Gradle plugin to be configured from "plugins" DSL

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#427]
## Description
Publish plugin data for Dexcount gradle plugin? The AGP and Kotlin plugins do this already. I have found this: https://plugins.gradle.org/plugin/com.getkeepsafe.dexcount/3.0.0-SNAPSHOT. Looks like we might just need to update the plugins repo with the latest?

## Example (currently in production)

Using`buildscript`:
```
buildscript {
  repositories {
    google()
    mavenCentral()
  }

  dependencies {
    classpath("com.android.tools.build:gradle:7.0.4")
    classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10")
  }
}

apply {
  plugin("com.android.application")
  plugin("org.jetbrains.kotlin.android")
}
```

Using `plugins`:
```
plugins {
  id("com.android.application") version "7.0.4"
  kotlin("android") version "1.6.10"
}
```

# Proposal Example

Using`buildscript`:
```
buildscript {
  repositories {
    google()
    mavenCentral()
  }

  dependencies {
    classpath("com.getkeepsafe.dexcount:dexcount-gradle-plugin:3.0.1")
  }
}

apply {
  plugin("com.getkeepsafe.dexcount"))
}
```

Using `plugins`:
```
plugins {
  id("com.getkeepsafe.dexcount") version "3.0.1"
}
```

**Comment by benjamin-bader** [comment]
Hi Jared, nice to hear from you!  I'm a little surprised that this isn't already in place; will see what's up with that.

/me goes to check

Looks like we do in fact have this published already: https://mvnrepository.com/artifact/com.getkeepsafe.dexcount/com.getkeepsafe.dexcount.gradle.plugin/3.0.1

Maybe I'm missing something obvious though.  Do you have any idea why this wouldn't be resolving in your project?

**Comment by jaredsburrows** [comment]
@benjamin-bader Nice to hear from you as well! Thanks for the quick feedback. 

Maven has the latest but plugins.gradle does not?

I have tried it locally and updated my sample app here: https://github.com/jaredsburrows/android-gif-example/pull/159.

Maybe I can close this and we can update the docs and update the publishing for the gradle plugin repo?

**Comment by benjamin-bader** [comment]
ah, I must have forgotten to publish there.  an easy fix - uploaded.  please give it a try!

**Comment by jaredsburrows** [comment]
@benjamin-bader Thanks! My build(https://github.com/jaredsburrows/android-gif-example/pull/159) passed and the artifact is uploaded here(https://plugins.gradle.org/plugin/com.getkeepsafe.dexcount/3.0.1).
