### ISSUE TITLE
No such property: format 

### ISSUE THREAD

**Issue by bazted** [KeepSafe/dexcount-gradle-plugin#44]
Hello,
    thanks for great plugin.

I have  faced an issue while configuring plugin.

I have included this block in build.gradle of my application module.

dexcount {
    format = "tree"
}

But Gradle throws: 

Error:(88, 0) No such property: format for class: com.getkeepsafe.dexcount.DexMethodCountExtension_Decorated

I am using 
Gradle 2.10 via wrapper
Android gradle build plugin 1.5.0

**Comment by benjamin-bader** [comment]
Ack, sorry.  That's a documentation bug - that feature is in the latest snapshot builds, not the actual release.  I'll fix the readme.

**Comment by benjamin-bader** [comment]
...On second thought, I just released 0.4.0.  The configuration `format = "list|tree|yaml|json"` will work with the new version; expect it to hit Maven Central in the next 1-3 hours.

Please try the new version; if this still doesn't work for you, let me know.
