### ISSUE TITLE
Wrong counts?

### ISSUE THREAD

**Issue by Orbyt** [KeepSafe/dexcount-gradle-plugin#48]
Getting these numbers with this plugin:

Total methods in app-debug.apk: 138351
Total fields in app-debug.apk:  50498
Methods remaining in app-debug.apk: -72816
Fields remaining in app-debug.apk:  15037

I definitely dont have 138351 methods as im not using multidex so if I did have that many methods I would of gotten an error.

**Comment by benjamin-bader** [comment]
Haha, that's... odd.  Can you share the APK that you're using?

**Comment by Orbyt** [comment]
Yes its an application, using 0.4.1. So I just played with it a little, some things I noticed:

With multiDexEnabled set to true, the count is in the ~70k range, which sounds about right. If I comment out `multiDexEnabled true`, the count jumps to ~138k. Looking at the `debug.txt` file you mentioned, for the `android` package, that is listed at ~40k when multidex is disabled, and when its enabled that goes down to ~20k.

Hope that helps.

**Comment by benjamin-bader** [comment]
Thanks for the info.  Would you be able to post the debug.txt file as a Gist or a Pastebin, and link it here?  That would be a tremendous help in nailing down the bug.

Interesting that multidex cuts the `android` package in half.  Also interesting that you can even build at all to the point that you are even getting method counts - in my experience non-multidex builds with over 65K methods just fail.  Any idea why yours might be different?

**Comment by Orbyt** [comment]
I can post the `debug.txt` file later, if needed. I dont think that its building with 138k methods, I think that the count is off. I am targeting minSdk21, so using ART instead of Dalvik apparently, and http://developer.android.com/tools/building/multidex.html mentions some things about the ART runtimes optimizations for multidex, so perhaps it has something to do with that.

**Comment by benjamin-bader** [comment]
Thanks, I'd very much appreciate seeing `debug.txt`; it will help me work backwards and figure out what is being counted incorrectly.

I strongly suspect that the plugin is just double, triple, or quadruple-counting methods.  Even targeting API 21+, builds over 65K should just fail.

One other way to verify, above and beyond posting `debug.txt`, is to actually examine `app-debug.apk`.  I'm sure you're familiar with the APK format.  If you unzip it and find `classes.dex`, what's the output of the following bash command: `cat classes.dex | head -c 92 | tail -c 4 | hexdump -e '1/4 "%d\n"'`

**Comment by benjamin-bader** [comment]
Hi there, any update?  Is this still an issue for you?  If so, will you have time to upload `debug.txt`?

**Comment by Orbyt** [comment]
@benjamin-bader Unable to reproduce atm due to the project evolving. I do remember that command printing ~65-70k iirc. 

Here is the debug.txt that was generated when I was investigating this issue: https://gist.github.com/Orbyt/90aa5f3087b24d64162a

**Comment by benjamin-bader** [comment]
Thanks for posting that - definitely looks like double-counting, somehow.  This gives me something good to go on.

**Comment by jaredsburrows** [comment]
@Orbyt Are you still seeing this issue?

**Comment by Orbyt** [comment]
Not currently using the plugin @jaredsburrows

**Comment by benjamin-bader** [comment]
For anyone else who is facing this problem, PR #78 should address this.  It will land in the next day or two, barring unpleasant surprises.  Because the OP is no longer having a problem, I'm going to close this issue.

Thanks for your help, Orbyt.
