### ISSUE TITLE
Ability to exclude packages from counting process

### ISSUE THREAD

**Issue by outlying** [KeepSafe/dexcount-gradle-plugin#49]
It's a little related to #10 , I'm using dexcount with sample project to count my library methods and fileds, but in sample project I'm using Android support library, which is not used in my own library.

If I would be able to exclude whole 'android.support' package from counting process that would give me better feeling how big my library is. This could be done via Gradle configuration and it would be partial solution for #10

**Comment by benjamin-bader** [comment]
Hi, thanks for your suggestion (and your patience while waiting for a resonse).

This is something that could be done in one shell command - i.e. `grep "com.my.library" app/build/outputs/dexcount/debug.txt "com.my.package"`; my first thought is that the cost of maintaining new plugin code to do this outweighs the cost of grepping.

**Comment by outlying** [comment]
Sure I agree, but having this feature inside plugin provides some benefits
- easier to configure
- for many variants we don't need to grep each file
- we don't need to add extra build step / script to CI
- we can use Gradle to modify excluded list / add some extra logic if needed

**Comment by kenyee** [comment]
This isn't related to Issue #10 
I can see how it might be useful...just need an array of prefixes to exclude when counting stuff in packages.

**Comment by benjamin-bader** [comment]
(4 years later 😅)

The original motivation for this issue was a desire to not count the android support libs when counting a sample project for a library.  For years now we've been able to count methods in AARs directly, which should satisfy this specific use case.

Are there other reasons why this would be useful?

**Comment by benjamin-bader** [comment]
Closing due to no action for four years.
