### ISSUE TITLE
Add integration test

### ISSUE THREAD

**Issue by benjamin-bader** [KeepSafe/dexcount-gradle-plugin#53]
#50 looked good but failed at runtime with a MethodNotFoundException (#51).  This is not the first time a non-functional piece of code has landed; we should have an actual Android project built as part of the Travis build.

Not sure how much Travis will support this, but we can figure something out.

**Comment by karlicoss** [comment]
@benjamin-bader it can probably be just a separate project. Not a proper CI, but you could at least add its Travis badge in readme as well, so any failures will still be noticed quickly
