### ISSUE TITLE
Dexcount plugin requires the Android plugin to be configured

### ISSUE THREAD

**Issue by MarKco** [KeepSafe/dexcount-gradle-plugin#55]
Hello,
when I try and build my project after I add the library I get the following error:

Error:(18, 0) Dexcount plugin requires the Android plugin to be configured

this is my app build.gradle file

// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.0.0-beta5'
        classpath 'com.google.gms:google-services:2.0.0-alpha3'
        classpath "net.rdrei.android.buildtimetracker:gradle-plugin:0.5.+"
        classpath "com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.4.2"
    }
}

apply plugin: "build-time-tracker"
apply plugin: "com.getkeepsafe.dexcount"

dexcount {
    format = "list"
    includeClasses = false
    includeFieldCount = true
    includeTotalMethodCount = true
    orderByMethodCount = false
    verbose = false
}

buildtimetracker {
    reporters {
        csv {
            output "build/times.csv"
            append true
            header false
        }

        summary {
            ordered true
            threshold 50
            barstyle "unicode"
        }

        csvSummary {
            csv "build/times.csv"
        }
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

What do I need to configure?

Thank you

**Comment by benjamin-bader** [comment]
Looks like you're in the root build.gradle file; you need to put dexcount config in the app build.gradle file, which is usually `app/build.gradle`.

**Comment by MarKco** [comment]
That was embarassing -.-
Thank you for your kind answer, this of course solved the issue.

**Comment by benjamin-bader** [comment]
Glad I could help!

**Comment by ChristopheVersieux** [comment]
That's exactly what I did, but I still ghet the same message...
