### ISSUE TITLE
Result visualization

### ISSUE THREAD

**Issue by danikula** [KeepSafe/dexcount-gradle-plugin#56]
Is it possible to generate some html report with visualized result for example with pie chart or histogram ?

**Comment by benjamin-bader** [comment]
Anything is possible, but visualization would be better done with another tool like Jenkins, Google Sheets, or Excel.

That said, I'm happy to accept pull requests!  If you decide to implement this, the only thing I'd ask is that there be no additional configuration options; this kind of output should always be generated unconditionally.  Maybe under 'app/build/reports'?

**Comment by benjamin-bader** [comment]
Released in 0.4.3
