### ISSUE TITLE
I want to know which methods is deleted from debug to release

### ISSUE THREAD

**Issue by tinybright** [KeepSafe/dexcount-gradle-plugin#58]
I want my proguard doesn't to delete some method.
release  debug   package/class name
2             1            com.ui(deleted A.class)

**Comment by benjamin-bader** [comment]
`diff build/outputs/dexcount/debug.txt build/outputs/dexcount/release.txt`

Make sure that both of those files exist, i.e. build debug then release without cleaning in between.

**Comment by benjamin-bader** [comment]
Looks like there is nothing to do here; diffing debug and release builds is out-of-scope.
