### ISSUE TITLE
It can work work instant run

### ISSUE THREAD

**Issue by tinybright** [KeepSafe/dexcount-gradle-plugin#59]
[Total methods: 384
methods  fields   package/class name
181      18       java
77       13       java.lang
10       0        java.lang.reflect
1        0        java.lang.ref
0        5        java.lang.annotation
56       1        java.io
42       3        java.util
7        0        java.util.zip
5        0        java.util.jar
3        3        java.util.logging
3        0        java.security
2        0        java.math
1        1        java.nio
1        1        java.nio.charset
156      67       com
156      67       com.android
156      67       com.android.tools
156      67       com.android.tools.fd
151      53       com.android.tools.fd.runtime
5        14       com.android.tools.fd.common
42       2        android
14       0        android.util
12       0        android.app
8        1        android.content
3        0        android.content.res
0        1        android.content.pm
6        0        android.net
2        0        android.widget
0        1        android.os
5        0        dalvik
5        0        dalvik.system
](url)

**Comment by benjamin-bader** [comment]
I've never tried Instant Run, so have no idea how it works.  Is that what is produced when you build with it?  Is this different from what you would expect?

**Comment by tinybright** [comment]
You can have a try. I have 60k mehods.But in instant run,it shows only 180.

**Comment by benjamin-bader** [comment]
I see.  When you do a regular build though, is the method count accurate?

**Comment by tinybright** [comment]
It's  accurate mostly though there is 2 dex file when it says I only contain 64k methods.

**Comment by zsavely** [comment]
I have the same issue. When I upload my APK to NimbleDroid, it shows over 65k methods. But in the build log it shows this:
> Total methods in demo-debug.apk: 373 (0,57% used)
> Total fields in demo-debug.apk:  88 (0,13% used)
> Methods remaining in demo-debug.apk: 65162
> Fields remaining in demo-debug.apk:  65447

It started to happen when I switched to Android Studio `2.0` and Android Plugin for Gradle `2.0.0`.

**Comment by benjamin-bader** [comment]
We just updated our build to 2.0, I see the same thing in Instant Run.

I have to think about a solution; as a gradle plugin, all we see is the output of the build process, which under Instant Run is sometimes incremental.  Maybe the new build tools have an augmented data model we can use?

**Comment by benjamin-bader** [comment]
I've opened PR #78 to add support for Instant Run builds.  It's a pretty large change, and I'd appreciate any help I can get.  It would be very helpful if someone could pull down the PR, build it, and try it out on their own projects.  The short version of how to do so:

1. Clone the repo, check out PR 78
2. In the repo, `./gradlew install`.  This will build the plugin and install it to your local Maven cache
3. In your `app/build.gradle`, add:
```
buildscript {
  repositories {
    mavenLocal() // make sure this is at the top
    ...
  }

  dependencies {
    classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.4.5-SNAPSHOT'
  }
}
```
If you find any problems, please comment here or on the PR and let me know.

One thing to note: Instant Run adds instrumentation to all of your code - one extra field per class, and a few hundred methods.  Instant Run builds *will have larger method and field counts*.

One thousand thanks to all of you!
