### ISSUE TITLE
adding the dependencies trig a gradle error

### ISSUE THREAD

**Issue by Loda** [KeepSafe/dexcount-gradle-plugin#63]
I added the dependency in my main build.gradle file:

```
  repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.3.0'
        .....
        classpath 'com.getkeepsafe.dexcount:dexcount-gradle-plugin:0.4.3'
     }
```

When running ./gradlew clean ass
I get:

> Cannot filter assets for multiple densities using SDK build tools 21 or later. Consider using apk splits instead.

Extract of my main module's build.gradle:

```
apply plugin: 'com.android.application'
// apply plugin: 'com.getkeepsafe.dexcount' // notice: this is commented
....
android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    dexOptions {
        jumboMode = true
    }

    defaultConfig {
        .....
        minSdkVersion 9
        targetSdkVersion 21
        compileOptions {
            sourceCompatibility JavaVersion.VERSION_1_7
            targetCompatibility JavaVersion.VERSION_1_7
        }


        // The following line makes sure resources for other screen densities will not be packaged.
        // This is specially useful to reduce APK size as some libraries may package a lot of
        // unnecessary resources otherwise. [!] BEWARE: you'll need to include any new screen
        // density you want to support here
        resConfigs "nodpi", "ldpi", "mdpi", "hdpi", "xhdpi", "xxhdpi", "xxxhdpi"
    } //END of defaultConfig
    ....
}
```

Observation:
- my project compile fine without the dependency of dex-count

**Comment by Loda** [comment]
If I comment the "resConfig" lines, then I got:

> com.android.dex.DexException: Multiple dex files define Ljavax/annotation/CheckForNull;

annotation which I do not use in my code. (but probably some lib I import use it)

**Comment by benjamin-bader** [comment]
Interesting.  To be honest I can't fathom why applying the dexcount plugin would interact with asset filters.  I've encountered similar behaviors with Gradle builds, where changing a random thing causes failures elsewhere - it is usually a bug in the Android build tools.  In this case, the error message seems suggestive to me; Android build tools seem to think that asset filters shouldn't work at SDK 21 or above.  Do they work when dexcount is commented out?

Your second error is clearer - once you figure out what lib depends on this, you can just exclude the transitive dependency:

```
compile ('com.foo.bar:my-lib:1.0.0') {
  exclude module: 'third-party-lib'
}
```

**Comment by Loda** [comment]
Yes, the error only show up when I declare the class path.

Yes, i could remove the transitive dependency. But, why does this error
show up now is a mystery to me.
I mean, your plug in should not add anything to my compiled code....
Specially if I only import it but don't use it.

**Comment by benjamin-bader** [comment]
Oh!  This bug happens just from declaring a classpath dependency?  This sounds very much like a bug we keep hitting in our project, where adding classpath dependencies (not dexcount, incidentally) fails the build, even if they are unused.  It's certainly an ABT error, and one that they seem in no hurry to fix.

Or do I misunderstand?

It's true, the plugin does not add anything to your compiled code, nor does it affect (intentionally, at least) the set of input classes to `dx`.

**Comment by benjamin-bader** [comment]
Wild guess that probably won't fix anything, but does `./gradlew clean` change anything?

**Comment by Loda** [comment]
Correct. Notice in the example attached to the issue, the "apply plugin"
is commented

Thanks for suggesting the grade clean. I tried that already (every time I
hit a weird compilation error, I do a clean)

More than anything, I wanted to know if you can reproduce it. If so, we
could report it to Google then.

Precision : I compile on Ubuntu, from the shell.

**Comment by benjamin-bader** [comment]
OK.  I'll try to repro this tonight, but can't promise any results.  Thanks for reporting it; if I find anything, I'll update/re-open this issue.
