### ISSUE TITLE
Add support for Android libraries

### ISSUE THREAD

**Issue by jaredsburrows** [KeepSafe/dexcount-gradle-plugin#65]
It would be really helpful to add support for Android libraries, specifically for developers that write SDKs. for Android.

**Comment by benjamin-bader** [comment]
Are you referring to AARs?  If so, this is a duplicate for #10 and it's not a priority for me.  To summarize, method counts of AARs are inaccurate b/c methods references in AARs are de-duplicated during dexing; what you get from counting methods in the class files is not at all what you get when you add the lib to your app.  I'm happy to accept a PR that does this, but as the output cannot but be inaccurate I will not be working on this myself.

...or, are you asking about something else?

**Comment by jaredsburrows** [comment]
@benjamin-bader I did not see that issue. Thanks for linking it. I just wanted to add this request here.

**Comment by jaredsburrows** [comment]
This is a duplicate of #59.
