### ISSUE TITLE
Enhancement: order by method counts

### ISSUE THREAD

**Issue by IgorGanapolsky** [KeepSafe/dexcount-gradle-plugin#7]
Hi,
is there any way you can modify your plugin to spit out the report which is ordered by method count?  Otherwise I have to scroll through a very large file every time and look for packages haphazardly.

Thanks,
Igor

**Comment by benjamin-bader** [comment]
That's a good idea; I'll add that to the list.  Until the next release, if you are on linux or a mac you can use the command line to see this info quickly:

```
cat app/build/outputs/dexcount/debug.txt | sort -nr | less
```

**Comment by IgorGanapolsky** [comment]
@benjamin-bader Thanks for this plugin.  @changetip $1.

**Comment by changetip** [comment]
Hi @benjamin-bader, @IgorGanapolsky sent you a Bitcoin tip worth 3,529 bits ($1.00), and I'm here to deliver it ➔ **[collect your tip](https://www.changetip.com/collect/872174)**.


**[Learn more about ChangeTip](https://www.changetip.com/tip-online/github)**

**Comment by benjamin-bader** [comment]
This is implemented in master, and will be available in the latest 0.2.0-SNAPSHOT build within an hour or two of writing.  Sorry for the delay, I've had other priorities over the past month or two.
