### ISSUE TITLE
Does this work after or before progaurd ?

### ISSUE THREAD

**Issue by KhalloufHassan** [KeepSafe/dexcount-gradle-plugin#87]
Hi,
Thanks for this plugin it's really amazing!

I just wanted to know does this work before or after progaurd? I have way too many methods and can't tell if those methods are before or after shrinking

**Comment by benjamin-bader** [comment]
Hi, thanks!

This works after proguard; how many is way too many?  In my experience a brand-new app with zero code but including the SDK and support libraries is already around 34K methods, pre-Proguard.  With Proguard it's down to a few thousand.

Also, I've definitely been bitten by Proguard not running when I think it should.  You can verify that Proguard is running by checking for `app/build/outputs/mapping` - if that doesn't exist after building, then Proguard isn't being run.

**Comment by KhalloufHassan** [comment]
Thanks that was really helpful, I was searching on how to know if proguard is enabled or not.

I had 96K methods, but it turned out my Progaurd wasn't running.

I just upgraded to android studio 2.0 and didn't know that the instant run feature disables Proguard automatically, I turned it off and it shrank to 44K methods

Thanks again for this plugin :+1:

**Comment by benjamin-bader** [comment]
Instant Run really messes with you!  The plugin isn't really well-tested with Instant Run by me, at least, because if I turn it on my builds crash on startup.  Thanks for giving it a whirl.
