### ISSUE TITLE
Feature request: save dex count history

### ISSUE THREAD

**Issue by laomo** [KeepSafe/dexcount-gradle-plugin#91]
Now my solve it like this:

```
      gradle.taskGraph.afterTask { Task task, TaskState state ->
        if (task.name == "assembleProductDebug") {
            if (!state.failure) {
                exec {
                    executable './scripts/dexcount.sh'
                }
            }
        }
    }
```

dexcount.sh:

```
#/bin/bash

if [ ! -f dexcount/productDebug.csv ]; then
    mkdir dexcount
    echo "time,methods,fields,change" >> dexcount/productDebug.csv
fi
content=`sed '2!d' app/build/outputs/dexcount/productDebug.csv`

latest=`sed  -n  '$p' dexcount/productDebug.csv| awk -F "," '{print $2","$3}'`

if [ "$content" != "$latest" ]
    then
    timeStr=`date '+%Y-%m-%d %H:%M:%S'`
    echo $timeStr,$content>> dexcount/productDebug.csv
    echo "dexcount changed !"
fi
```

**Comment by benjamin-bader** [comment]
I like the functionality, but from my first impression it seems like it might be at odds with the usual output of a build system.  For example, right now `./gradlew clean` will delete all dexcount output.  How are you thinking this feature would behave when cleaned?

**Comment by laomo** [comment]
@benjamin-bader save history to  `$PROJECT_DIR/dexcount/productDebug.csv` ensure this.

**Comment by benjamin-bader** [comment]
It's been over a year since this was opened; please accept my apology for leaving this open for so long.

I don't believe that this feature is within the scope of a build plugin - it shouldn't have artifacts that outlast a `clean`.  A CI system is the natural owner for this sort of job.  Accordingly, I'm closing the issue.
