### ISSUE TITLE
Plugin with id 'com.getkeepsafe.dexcount' not found.?

### ISSUE THREAD

**Issue by yanglichuan** [KeepSafe/dexcount-gradle-plugin#92]
Plugin with id 'com.getkeepsafe.dexcount' not found.

**Comment by benjamin-bader** [comment]
You need to add the plugin as a classpath dependency under `buildscript`.  See the `Usage` section of README.md for an example.

**Comment by benjamin-bader** [comment]
Any update - were you able to get things working?

**Comment by benjamin-bader** [comment]
I'm guessing that you were able to fix things; closing the issue now.
