### ISSUE TITLE
Disabling the plugin?

### ISSUE THREAD

**Issue by Macarse** [KeepSafe/dexcount-gradle-plugin#98]
Which is the best way to disable the plugin for certain runs?
I just want to run it during my app's nightly build.

**Comment by benjamin-bader** [comment]
I'd set a Gradle property that's true for nightly builds, and do something like:

```
def isNightly = hasProperty('nightlyBuild') && nightlyBuild

if (isNightly) {
  apply plugin: 'com.getkeepsafe.dexcount'
}
```

**Comment by benjamin-bader** [comment]
Does this help?  Please let me know so that I can close the issue or help out in some other way.

**Comment by Macarse** [comment]
@benjamin-bader: Sorry for the delay.
 
I would prefer not to pollute my `build.gradle` file nightly build variables.
I was looking for something like:
```
gradle build -x lint
```
but the plugin doesn't have a task associated to it.

**Comment by benjamin-bader** [comment]
It does, as of 0.5.1 - `count${variant}DexMethods`, where `variant` is Debug, Release, or whatever flavor you happen to be building.  I haven't tried this, but I'm assuming that if you build multiple variants you will need to suppress all variants of the counting task.

**Comment by Macarse** [comment]
Oh, interesting. My Flavor is normalDebug.

I don't understand why if there is a task `countNormalDebugDexMethods`, I don't see listed in the logs when I do `./gradlew assembleNormalDebug` :(

Doing `./gradlew tasks` listed countNormalDebugDexMethods, so it is there.

Unfortunately, if I run `./gradlew assembleNormalDebug -x countNormalDebugDexMethods`, the task is still running. Any idea?

**Comment by benjamin-bader** [comment]
Are you using version 0.5.2?  On my build (whose flavor is 'mainline'), I just ran `./gradlew assembleMainlineDebug -x countMainlineDebugDexMethods`; the plugin did not run.

Prior to 0.5.1, the plugin code that handled task registration was pretty broken, and would result in exactly the behavior you describe.

**Comment by Macarse** [comment]
cool! Now it works!

Thanks!
